### ISSUE TITLE
Difference between those two url ?

### ISSUE THREAD

**Issue by zhengqiang1307** [ice-wm/icewm#1]
I wonder the relationship between https://github.com/ice-wm/icewm/ and https://github.com/bbidulock/icewm/, and if I write a "url" or "source" tag in a spec file, which one is right ?

Url:                 http://www.ice-wm.org/
Source0:        https://github.com/bbidulock/%{name}/releases/
or
Source0:        https://github.com/ice-wm/%{name}/releases/

Thanks.

**Comment by gijsbers** [comment]
Good question. The first is for stable releases for end-users. 
The second is for development. It may have unresolved problems.

The website URL is preferably given as https://ice-wm.org.
For an example spec file which is up to date you can consult:
https://github.com/OpenMandrivaAssociation/icewm/blob/master/icewm.spec
