### ISSUE TITLE
icesh -X filter? - Multimonitor setup.

### ISSUE THREAD

**Issue by TinkerforFunandAutonomy** [ice-wm/icewm#10]
IceWM 1.6.4

I'm trying to make a script so I can have some of the functionality from a "tiling windowmanager".

I can't get the -X filter to work. 

icesh randr
0: 1920x1200+0+1080
1: 1050x1680+1920+645
2: 1920x1080+0+0

icesh -a -X 0 list
Gives me all windows and not only the ones on monitor 0.
icesh -X 0 list 
icesh: No windows found
(Am I reading the manual wrong? If no selctor is given -all is assumed).

icewm --configured
icewm configured options: alsa ao fdomenus fribidi gdkpixbuf i18n librsvg libxpm nls oss session shape wordexp xfreetype2 xinerama xrandr

I can't find an option til list what Windows a currently selected.

With regards and appretiation for your work.

**Comment by gijsbers** [comment]
That piece was yet unimplement. Done. Thx.

**Comment by TinkerforFunandAutonomy** [comment]
Thank you!
