### ISSUE TITLE
taskbar does not reflect currently selected workspace until I release Ctrl+Alt

### ISSUE THREAD

**Issue by lersek** [ice-wm/icewm#109]
Not sure when this behavior changed, but it's weird (I've recently switched from 1.3.7 to 3.2.2).

Steps to reproduce:
1. select Workspace#2
2. close all windows here
3. select Workspace#1
4. close all windows here
5. open a new window (start an xterm, whatever) on Workspace#1
6. press and hold `Ctrl+Alt`
7. press and release `2`, but *hold* `Ctrl+Alt` (alternative step: press and release `Cursor Right`, but *hold* `Ctrl+Alt`)
8. the desktop contents change (the window opened on Workspace#1 disappears from the main desktop area, as expected), but the taskbar is *not* updated. It still shows the button for the window from Workspace#1.
9. *Release* `Ctrl+Alt`.
10. The taskbar is now updated.

Desired behavior: the taskbar should, at all times, reflect the main desktop area, not just when `Ctrl+Alt` are released.

I assume this is intentional behavior, hence my filing this as a discussion and not as an issue.

What new preference can I use to restore the original behavior? Thank you.

_Originally posted by @lersek in https://github.com/ice-wm/icewm/discussions/108_

**Comment by gijsbers** [comment]
See bbidulock/icewm#549.

**Comment by lersek** [comment]
@gijsbers thanks for the pointer, but I'm none the wiser :)

What @zaza42 describes [here](https://github.com/bbidulock/icewm/issues/549#issuecomment-1314397731) and what @danfe describes [here](https://github.com/bbidulock/icewm/issues/549#issuecomment-1315425050) is precisely my use case. How was it solved? 

A reference to commit f074fb0cf405b9ec5191cd942c52c334c5ca1970 was made, and I've checked that commit now -- it does not introduce any new preference setting as far as I can tell, and it certainly does not solve the symptom I'm seeing. The commit has nearly zero documentation, the subject line says `Only freeze task pane layout when a button was removed`. The commit also does not seem to be a part of a larger patch series (it stands alone between f8a935a6d722c3b54f711dd0cfcc141120f7337c and ecc2bf2f54ab1bdd7e6e39930f546c17f865f236).

Can you please explain? Thank you.

**Comment by lersek** [comment]
... Aha, I got it now. Commit f074fb0cf405b9ec5191cd942c52c334c5ca1970 is part of tag 3.2.3, and I'm running 3.2.2 presently. I installed [IceWM](https://koji.fedoraproject.org/koji/packageinfo?packageID=2099) from EPEL9 on 2022-12-07, and back then, 3.2.3 had not yet been packaged for EPEL9. But now it has been, so I'll pick it up. Many thanks!
