### ISSUE TITLE
Disable Super key opening WindowList

### ISSUE THREAD

**Issue by Brottweiler** [ice-wm/icewm#11]
I cannot find any setting to disable that Super key opens the WindowList. The closest I can find is `KeySysWindowList="Alt+Ctrl+Esc"` which _obviously_ isn't what I am looking for.

How do I disable it? Is there a way?

Edit: Actually, right Super key opens WindowList, but the left one opens the Menu. How can I control this?

**Comment by gijsbers** [comment]
try `Win95Keys=0`.

**Comment by Brottweiler** [comment]
Ah! Thanks, that worked.
