### ISSUE TITLE
focus not transfered to line-edit Motif widgets in xnedit

### ISSUE THREAD

**Issue by lersek** [ice-wm/icewm#110]
I'm having an issue similar to #88, but I'm unsure if it is the same. It's also difficult to reproduce; it looks non-deterministic.

I use a Motif application called [xnedit](https://github.com/unixwork/xnedit). Since switching IceWM from version 1.3.7 to 3.2.2, sometimes when xnedit pops up a dialog, with a line-edit widget *nominally* focused, the focus isn't actually transfered to that widget. As soon as I start typing, the characters I enter end up in the wrong window.

For example, I open the search dialog and start typing an expression immediately, or open a tag lookup window and start typing a function name immediately, and the text ends up in the source code "from which" I just opened the dialog.

**Comment by lersek** [comment]
Hello @gijsbers , one remark and a question:

1. I think this ticket may be a duplicate of https://github.com/bbidulock/icewm/issues/400
2. What is the actual upstream repository for IceWM? Minimally, the bug tracker should not be split between two projects. This project is called `ice-wm`, and the *release links* on https://ice-wm.org/ point here. But there is also of https://github.com/bbidulock/icewm , and the *github link* on https://ice-wm.org/ points there. In other words, the presumed icewm homepage is itself inconsistent. So what github project exists for what purpose? Are you handling "releases only" here, and I was wrong to report issues here rather than at https://github.com/bbidulock/icewm ? (Because, well, my issues are not related to the release process or artifacts, but the source code.) Thanks.

**Comment by gijsbers** [comment]
Please look for pointers on how to post your issues beforehand:

1. [This](https://github.com/ice-wm/icewm) shows on the top right side a request to read the [Wiki](https://github.com/ice-wm/icewm/wiki). 
2. [The README](https://github.com/ice-wm/icewm/blob/master/README.md#bug-reports) is also clear.
3. [The website](https://ice-wm.org/#bug-tracking) is also clear.
4. The BUGS section of the icewm manpage.
5. The output of `icewm --help`.

**Comment by gijsbers** [comment]
I could reliably reproduce this bug. This commit fixes it for me. Can you test if it works for you too? Thanks.

**Comment by lersek** [comment]
Thank you for looking into this. Can you please share your reproducer? As I've noted earlier, for me the symptom pops up rarely. It's frequent enough to be distracting but not frequent enough for me to reliably trigger it. I've been unable to isolate the circumstances upon which it depends. Right now I've opened the Find dialog in xnedit about 25 times with `Ctrl+F`, and the issue did not reproduce. Without a reliable reproducer on my end I cannot confirm (not within a short time period anyways) whether the patch makes a difference. Sorry about the hassle.

**Comment by gijsbers** [comment]
Just Ctrl+F didn't bug, but opening the search dialog via the menu always did. The fix is in 3.3.0.

**Comment by lersek** [comment]
Thanks, that reproducer works reliably for me as well, and indeed 3.3.0 fixes the issue. Kudos.
