### ISSUE TITLE
"Dynamic" battery status monitor on task bar when removing/reinserting battery

### ISSUE THREAD

**Issue by T-3B** [ice-wm/icewm#117]
With my laptop, I'm used to remove the battery when I'm working home.

But if I reinsert it, the taskbar won't show the battery monitor on the taskbar.

I tried `icesh -T restore`, which obviously did not change anything.

So now I set `TaskBarShowAPMStatus=1`, which will force the battery monitor to be displayed even if there is no battery.

From what I saw:
- If I start icewm with the battery, its monitoring will be as expected (battery capacity shown, when removed the monitor goes to black, and if I reinsert the battery the monitor will update correctly).
- If I start icewm with**out** the battery, and then inserting it, the monitor won't update (which is the issue).

Since the expected behaviour happens when starting icewm with a battery, I suppose (and hope) the fix is not that difficult.

**Comment by Code7R** [comment]
And you are running which OS? Linux? Which kernel?

If Linux: please run "find /sys/class/power_supply/*" with and without battery and compare the results.

**Comment by T-3B** [comment]
ArchLinux, latest stable kernel (6.1.5-arch2-1).

There is no problem with `/sys/class/power_supply/BAT0`, it shows when the battery is (re)inserted.
The iceWM monitor battery does not follow that sys file existance when it was started without a battery (thus only `/sys/class/power_supply/AC`).

**Comment by gijsbers** [comment]
Contrary to your supposition, it is difficult and a lot of work. Consider [this article](https://stackoverflow.com/questions/67852156/listening-for-sysfs-battery-events). An event needs to be listened for. These techniques and library calls need to be shoehorned into the existing infrastructure. Ports to OpenBSD and FreeBSD need to be made. Maybe it needs to be documented and explained to users. People may discover bugs, which need to be investigated, solved and released. Why don't you just `icewm -r`?

**Comment by Code7R** [comment]
I was about to write the same. Could not figure out any sensible way without using lots of sysctls and without being root.
Maybe apply a very dumb scheme and run a glob() on that folder every 30 seconds?

**Comment by T-3B** [comment]
Did not that `icewm -r` don't kill any app running, and for my use I think it is sufficient.

Thank you for your fast answers!
