### ISSUE TITLE
XDG icons do not work

### ISSUE THREAD

**Issue by Brottweiler** [ice-wm/icewm#12]
At least that is what I think they are called. Basically I am talking about when apps have icons such as `utilities-terminal` or `preferences-desktop-theme`. When you specify these as icons in `menu` they do not show, and the menu entry has no icon. Example:
```
prog LXAppearance preferences-desktop-theme lxappearance
```

Same goes for default menu entries that I haven't even added myself, such as folders that do not have the folder icon, like `Education` and `Graphics`.

It also seems like the Start Menu icons do _not_ use my icon theme, how come?

**Comment by gijsbers** [comment]
Do `icewm --trace=icon` to see what icons it finds where.
Examine IconPath and tell us what is wrong for you.

**Comment by gijsbers** [comment]
Or `Trace="icon"` in preferences.

**Comment by Brottweiler** [comment]
> Do `icewm --trace=icon` to see what icons it finds where.
> Examine IconPath and tell us what is wrong for you.

Can't run this because it says `A window manager is already running`.

> Or `Trace="icon"` in preferences.

Did this, what do I do now? Is there a log file somewhere I should check?

**Comment by gijsbers** [comment]
icewm has a --replace option. This is explained in the icewm man page.
Or you could start a virtual display with Xephyr and use that.

Did you try `ls -ltra ~` to locate a possible log file?

Where are your utilities-terminal and preferences-desktop-theme located?
Can you find those locations in the output of

    icewm -p | grep IconPath

If not then what happens if you add them?

**Comment by Brottweiler** [comment]
Ah, yes. Adding my icon theme into the `IconPath` solves the issue. Thanks.

**Comment by gijsbers** [comment]
You could help us improve things if you would explain what you did exactly with details.

**Comment by Brottweiler** [comment]
I'll add a comment here tomorrow when I'm back at my computer!

But basically, I just added the path to my icon theme to `IconPath`. `/usr/share/icons/Papirus` in this case.

But I'll show exactly what I did tomorrow.

**Comment by Brottweiler** [comment]
```bash
#  Icon search path (colon separated)
IconPath="/usr/share/icons/Arc:/usr/share/icons/Papirus:/usr/share/icons/oxygen/base:/usr/share/icons/Adwaita:/usr/share/icons/hicolor:/usr/share/icons:/usr/share/pixmaps:/usr/local/share/icons/hicolor:"
```

So I simply added `/usr/share/icons/Arc:/usr/share/icons/Papirus` which is the themes I use. The Arc theme only has icons for folders and some stuff to match my Arc GTK theme, and Papirus has app icons.
