### ISSUE TITLE
HideBordersMaximized and HideTitleBarWhenMaximized

### ISSUE THREAD

**Issue by developer1105** [ice-wm/icewm#121]
These two properties seem to be malfunctioning: HideBordersMaximized and HideTitleBarWhenMaximized.

In any theme, HideBordersMaximized always hides borders when maximized, regardless of the state of the property. 
HideTitleBarWhenMaximized always shows the title bar when maximized, regardless of the state of the property.

I was trying to do a theme to emulate the appearance of pekwm on icewm, and it would be interesting if the borders could appear in windows, even when they are maximized to get the same effect.

The icewm version is 3.3.1-1 running on arch linux.

**Comment by gijsbers** [comment]
Works fine here. They hide when enabled and show when disabled. Theme CoolSteel.

**Comment by developer1105** [comment]
Okay. Tell me about some details:
Which distro are you using? What is the icewm's version? How did you install it?
I'm thinking about testing this in a virtual machine. Maybe it's an issue related to Arch Linux.

**Comment by gijsbers** [comment]
I recommend you use `antiX`. It may well be the best designed, best tested and best supported IceWM configured distribution.

I worry you may have improperly configured it. What is the output of `icewm -p | grep ^Hide`?

What Hide settings do you see in the menu `Settings -> Preferences -> A... - L...`?

**Comment by developer1105** [comment]
`HideTitleBarWhenMaximized` works only when it is set in the preferences (via menu or config file).

`HideBordersMaximized` does not work in both cases (.icewm/preferences or default.theme). 

I have tested this on a VM running antiX.

To test it, I am using the metal2 theme, from antiX (_it has very thick borders_). I choose a restored window, and then I resize it with the mouse, so that it occupies all the screen, but the borders are still visible. When clicking the maximize button, the borders disappear.

I don't know what behavior to expect from HideBordersMaximized, maybe it is something different from what I imagine.

**Comment by gijsbers** [comment]
The manpage explains which settings can be set by a theme:
https://ice-wm.org/man/icewm-preferences#theme-settings

If you don't know what behavior to expect, then you cannot be disappointed.
Again, the manpage informs you.

I contrast your initial statement:
> These two properties seem to be malfunctioning:

**Comment by developer1105** [comment]
I got ```HideBordersMaximized=false``` working now, 
but to achieve this, I had to set 
```ConsiderVBorder=true``` and 
```ConsiderHBorder=true```

**Comment by developer1105** [comment]
Although I set these (ConsiderVBorder/ConsiderHBorder) to true, and thus HideBordersMaximized=false starts working perfectly, I keep getting deprecated option errors on shutdown log:
```Warning: ConsiderVertBorder is deprecated```
```Warning: ConsiderHorizBorder is deprecated```

**Comment by gijsbers** [comment]
Clearly the message states that is a `Warning`. Hence it is not an error, like you state.

I explained before that only setting `HideBordersMaximized` suffices for me. There should not be a need to change the ConsiderBorder options. They can be removed from icewm code.
