### ISSUE TITLE
Path in menu file and .desktop, help please

### ISSUE THREAD

**Issue by Pro-pra** [ice-wm/icewm#122]
in my menu file not work:
includeprog icewm-menu-fdo 
prog Therminal terminal.xpm xterm

Work:
includeprog  /usr/bin/icewm-menu-fdo 
prog Therminal terminal.xpm /usr/bin/xterm

Why only with full path worked? 

Also .desktop files with Exec=foo (without full path) not visible in menu. May be need some environment setting (PATH is right, i check) or compile option?

**Comment by Pro-pra** [comment]
strace log:
```
newfstatat(AT_FDCWD, "xscreensaver-settings/:", 0x7ffe87d50310, 0) = -1 ENOENT (Нет такого файла или каталога)
newfstatat(AT_FDCWD, "xscreensaver-settings/:", 0x7ffe87d50310, 0) = -1 ENOENT (Нет такого файла или каталога)
newfstatat(AT_FDCWD, "/usr/bin/gparted", {st_mode=S_IFREG|0755, st_size=7201, ...}, 0) = 0
newfstatat(AT_FDCWD, "htop/:", 0x7ffe87d50310, 0) = -1 ENOENT (Нет такого файла или каталога)
newfstatat(AT_FDCWD, "htop/:", 0x7ffe87d50310, 0) = -1 ENOENT (Нет такого файла или каталога)
```

why program i see htop/: need htop?

**Comment by Pro-pra** [comment]
release 2.9.1 - not affected
release 2.9.2 - affected

**Comment by gijsbers** [comment]
Strange. What compiler version?

**Comment by Pro-pra** [comment]
gcc 11.2.0
