### ISSUE TITLE
Missing icons and patch

### ISSUE THREAD

**Issue by realsimix** [ice-wm/icewm#132]
Hi,

While running on RHEL9 I found that some icons were missing which were available on RHEL8. I then found how icons are searched and modified it for newer distributions.
I also looked at this https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#context to find out about some new specifications.

Find attached my patch which corrects the issues for me.
[icewm-3.3.4-icon_contexts.patch.txt](https://github.com/ice-wm/icewm/files/11406886/icewm-3.3.4-icon_contexts.patch.txt)

Regards,
Simon

**Comment by Code7R** [comment]
Looks trivial but I am wondering which kind of menu entries were affected. Could add some test examples, i.e. the .desktop files which ended have rendered without an icon?

**Comment by Code7R** [comment]
@gijsbert I added something similar and reworked it a bit, using find_if instead of the "strchr" optimization, see:

https://github.com/bbidulock/icewm/pull/new/feature/lookup-more-icon-sections

That said, it still did not work everywhere. I expected this to fix the loading of the keyboard icons (loading icons from iso-flags-svg package). But this reveals another strange issue - the icon for the first of KeyboardLayouts languges is drawn as a black box, and for the other ones it does not work and only text is drawn. There is no attempt to load their icons.

**Comment by gijsbers** [comment]
Thanks @Code7R.

@realsimix Could you give examples of icons (and their paths) which couldn't be found, but can now?

Do really all those directories have to be added? All these directory searches slow icewm down.

**Comment by realsimix** [comment]
I've just tested your commit [2f2afd9](https://github.com/bbidulock/icewm/commit/2f2afd96d715761458f4ce9693c3c5c77053ca54) and can confirm that it also fixes the issue.
Thanks!

**Comment by gijsbers** [comment]
Does it now also show icons for `Firefox`, `Sound & Video` and `Video` in your menu?
If you set `Trace=icon` in your preferences and restart, you'll see where it finds the icons.
That would be helpful to identify which directories are actually needed.

**Comment by realsimix** [comment]
No, the Firefox and other icons are not shown with the patch. This is on RHEL9 with a icewm build similar to the one in EPEL which adds an Adwaita theme to the package. So it's not a vanilla icewm and I also don't know if all required packages are installed on the test host :(

One thing I can say is that the Firefox package on RHEL9 only provides the following icons:
```
/usr/share/icons/hicolor/16x16/apps/firefox.png
/usr/share/icons/hicolor/22x22/apps/firefox.png
/usr/share/icons/hicolor/24x24/apps/firefox.png
/usr/share/icons/hicolor/256x256/apps/firefox.png
/usr/share/icons/hicolor/32x32/apps/firefox.png
/usr/share/icons/hicolor/48x48/apps/firefox.png
/usr/share/icons/hicolor/symbolic/apps/firefox-symbolic.svg
```

So, as long as icewm is not using `/usr/share/icons/hicolor/` to find icons it won't fine the Firefox icons.

Looking at the code I found this in the docs:
IconPath = /usr/share/icons/hicolor:/usr/share/icons:/usr/share/pixmaps

and this:

```
./icewm-3.3.4/src/yprefs.h:
XSV(const char *, iconPath,
                                                "/usr/local/share/icons:"
                                                "/usr/local/share/pixmaps:"
                                                "/usr/share/icons:"
                                                "/usr/share/pixmaps:"
```

and this:

```
./icewm-3.3.4/src/testmenus.cc:
    iconPath = "/usr/share/icons/crystalsvg/48x48/apps/:/usr/share/icons/Bluecurve/16x16/apps/:/usr/share/pixmap";

```
Needless to say this icon and theme handling is a bit a mystery to me.

**Comment by gijsbers** [comment]
I agree it is a bit complex. There are icon base directories set in `IconPath` and allowable theme subdirectories in `IconThemes`. 
```
IconPath="/usr/local/share/icons:/usr/local/share/pixmaps:/usr/share/icons:/usr/share/pixmaps:"
IconThemes="*:-HighContrast"
```
Is the default and looks OK to me. You can install more icon themes to your liking. Do `yum search icon-theme` and choose what you like. E.g., gnome-icon-theme seems to have more icons.
