### ISSUE TITLE
2 suggestions of enhacements for the toolbar and a problem with a dock

### ISSUE THREAD

**Issue by PPC-scripts** [ice-wm/icewm#136]
Hi!
First of all, many thanks for this almost perfect way to manage the desktop. as it is it's almost as feature rich as most D.E,'s.
I have only one issue, and suggestions:

**Issue** (not a major issue but some times problematic):
- As previously reported (on a closed issue)- when running plank dock, when the dock is not being displayed, the part of the screen that the dock takes once it's being displayed does not respond correctly to mouse input (it's like IcewM "thinks" the dock is being drawn, when it's not, and gets "confused" about how to process mouse clicks)

### Suggestions:
1- I love using the toolbar without displaying window titles, just the icons. I do have that set up, but the way that I know to achieve that is setting up the variable TaskbarButtonWidthDivisor to a certain value. the problem is that the value depends  on the available space in the taskbar, If there are too many quick launch icons, or too many items on the system tray, the icons for the currently running windows get either cut on the right side or display "..." after the icon. If it's not too hard to implement, it is possible to have a new setting, something like "TaskbarButtonHideText", to disable titles of windows on the taskbar, without having to adjust manually when the toolbar contents changes too much?
2- Another, probably harder to implement suggestion: I love the system tray resource indicators (I use only a square to present the current network info and another to show RAM/CPU/SWAP usage). Is there any simple way to add an indicator that displays the output of a command, at a given interval? Example: display network id, display battery percentage, display the weather (like "19º sunny", by running wttr on ansi weather, every hour or so, etc). 

Many thanks for your hard work!

**Comment by gijsbers** [comment]
- Isn't that a plank bug? The properties that plank advertises to icewm say that it wants to be 140 pixels high and cover the entire width of the display, even though it uses only a fraction of that screen area. Use `xprop` and `xwininfo` to see for yourself. Please report this bug in the appropriate plank forum.

1. The task button icons-only is asked more often. See bbidulock/icewm#633.
2. See #86. That is beyond the scope of this icewm forum.

**Comment by gijsbers** [comment]
See bbidulock/icewm#653.

**Comment by its-thomas** [comment]
I second the above mentioned IceWM and plank issue (see also [https://github.com/bbidulock/icewm/issues/653](https://github.com/bbidulock/icewm/issues/653))

I have just had a look at [https://launchpad.net/plank](https://launchpad.net/plank) and it seems like, the most recent plank version is dated 2019-08-19.

So I guess, even if I posted this as a bug report to the plank devs as suggested,  there won't be a plank update in the foreseeable future ...?

For me personally, that means if there is also no workaround from the side of IceWM, I would need to look for another WM unfortunately ..

Nevertheless, of course, I deeply appreciate all the hard, quality work that flows into the great piece of software that is IceWM!
Thanks a lot!

**Comment by gijsbers** [comment]
You could investigate which other WMs have a similar or dissimilar behavior. Whether those WMs are compositing or not. Whether they are small-memory WMs like IceWM or not.

**Comment by its-thomas** [comment]
According to this [post](https://www.antixforum.com/forums/topic/plank-on-fluxbox-or-icewm-doesnt-work-properly/), JWM does not have the mentioned problem:

> This issue does not take place in JWM.

**Comment by its-thomas** [comment]
To be exact:
I was using IceWM version 3.3.1-1 from the debian stable repositories. Any chance this issue might be fixed in the latest 3.4.2 version without anyone being aware of that?

**Comment by gijsbers** [comment]
Do you by chance run a compositor like picom? It works fine without (in 3.4.2).
Also try if the problem persists with jwm+picom.

**Comment by its-thomas** [comment]
Yes, I am using picom.

Without picom, plank in IceWM version 3.3.1-1 doesn't have the original issue of "partial dead screen", but it has some glitches when trying to start a program via clicking on the corresponding plank icon, which are quite hard on the eyes. Also, I feel like this is not a purely optical issue – clicking through those glitches, some programs won't open although I think they should or they only open when I click multiple times through the glitches ... that is not a pleasant work environment!

In JVM version 2.4.3-1 on the other hand, plank & picom seem to be working fine together. No "partial dead screen", no glitches.

Do you think you might be able to work this one out for plank, picom and IceWM as well?

**Comment by gijsbers** [comment]
Can you a screendump of the glitches? Or is there a better way to demonstrate this?
It may be a picom issue. See https://github.com/bbidulock/icewm/issues/653#issuecomment-1724201563.

**Comment by its-thomas** [comment]
Have a look at the following [screenrecording](https://gemoo.com/tools/upload-video/share/562494932113842176?codeId=DW4OQW9lZd8dm&card=562494928452214784). This issue exists only without picom, mind you!

**Comment by gijsbers** [comment]
The flickering you mean? I could understand that if plank first clears the window and then redraws everything. Although here the flickering is severe. A reliable method of drawing to avoid flickering is to use background pixmap to draw to and then set that background as the window background. I haven't experienced such flickering myself. Maybe a weakness in your video driver? Dunno.

**Comment by its-thomas** [comment]
Yes, the flickering only exists without picom. With picom, there's no flickering, but the "partial dead screen" issue.
 _Humph_

**Comment by gijsbers** [comment]
The thing is that this is the wrong place to make progress. People use icewm and experience a problem and then come here, even though icewm can't or won't do much about it. The flickering is a plank or video problem. The "partial dead screen" is a picom issue. Don't bother me about it.

**Comment by its-thomas** [comment]
I totally understand & share your point in general!

But in this specific case, my argument would be:
If JWM can handle plank and picom without the "partial dead screen" issue while IceWM cannot, then is this really a picom issue?

**Comment by gijsbers** [comment]
Yes, it is really a picom issue. They refrained from properly considering that some WMs use containers. I pointed you to my 653 comment above. Don't bother me about it.

**Comment by its-thomas** [comment]
>  They refrained from properly considering that some WMs use containers. I pointed you to my 653 comment above. 

OK. Fair point.

**Comment by gijsbers** [comment]
`plank.doNotManage: 1`

**Comment by its-thomas** [comment]
Thank you so much for your effort. I really appreciate it and I am sure, many other plank-in-IceWM-users as well!
