### ISSUE TITLE
Yad generated system tray icon does not display tooltips

### ISSUE THREAD

**Issue by PPC-scripts** [ice-wm/icewm#139]
As advised on other threads, I tried to create a system tray icon using yad. The icon correcly displays on the toolbar, but no tooltip is shown when the mouse pointer is placed on the icon. Other tooltips (like volumeicon or the system info squares) correctly display tooltips. If I swithc to other window manager, like jwm, and try again, the tooltip instantly comes up.
Tested on antiX 22 and antiX 23 beta (that include the latest icewm):

How to reproduce this:
1- On the terminal, run this command (that should display yad's default beaker icon on the system tray)
yad --notification --icon=mumbojumbo --tooltip="hi there"

2- Place the mouse pointer on the newly created icon. No tooltip comes up.

3- Switch to another window manager- like jwm- tooltip instantly comes up.

Possible icewm problem or a yad problem?

**Comment by cheapy** [comment]
PPC, try using 
    --text="$TRAY_TEXT"		
instead of
    --tooltip="$TRAY_TEXT"

**Comment by PPC-scripts** [comment]
Hi bob
I messed up, while writing the issue. I use --text="hi there". The tooltip
does not show up in icewm, but it does in jwm and fluxbox. Does that work
for you?

P.

BobC ***@***.***> escreveu no dia segunda, 19/06/2023 à(s)
18:45:

**Comment by cheapy** [comment]
![image](https://github.com/ice-wm/icewm/assets/7473967/c75f78d8-b464-4090-8740-ccca6314e1d0)
Yes, here was the code:
    	# create the notification icon in tray
	/usr/bin/yad --notification		            \
		--no-middle             	        \
		--icon-size="$Tray_icon_short_size"	\
		--image="$curr_icon"           		\
		--text="$TRAY_TEXT"					\
		--menu="$menu"                 		\
		--command="$default"  &

**Comment by PPC-scripts** [comment]
hum. Wierd. On icewm I get no tooltip. On jwm and fluxbox, running that
command, since the variable is empty, I get, as I should "yad tooltip" (or
something similar)

P.


BobC ***@***.***> escreveu no dia segunda, 19/06/2023 à(s)
19:04:

**Comment by cheapy** [comment]
I do wish IceWM had a built in "generic" tray icon where we could define an icon filename, size, tooltip text, command to run to update, number of seconds between updates, command to run on left click, and command to run on right click.  Updating would then refresh the icon filename, size, and tooltip text.  Right now, each tray icon uses as much or more memory than IceWM itself, so on low resource machines, they just can't afford to run them.

If a built-in option existed, I could use it for weather, root file space, home file space, sound control, updates available.  It could also be used to replace existing code that gets used to monitor emails, for example.

I have tried many times but I'm not a C or C++ programmer and not capable of writing it.

**Comment by gijsbers** [comment]
Such a project would take a life on its own. There is no reason it should be part of a window manager.

The yad systray icon shows a tooltip without problems. If it doesn't on your display, complain at yad headquarters.

**Comment by cheapy** [comment]
Yes, I understand.  At least we have a way to get them there for 11mb each.

Thanks for your help and efforts as always...

**Comment by PPC-scripts** [comment]
Hi Bob. I'm on my phone now... 
On my changes to the recent files menu- I forgot to mention that the script was created on the beta2. Anti changed the names of the scripts, adding yad to their start...  and has not yet pointed the menu entries to the new files. I fixed that, on my proposal...

Best wishes
Paulo

A 19 de junho de 2023 23:41:29 WEST, BobC ***@***.***> escreveu:
