### ISSUE TITLE
WorkspaceNames issue.

### ISSUE THREAD

**Issue by 5x3** [ice-wm/icewm#14]
try to switch from icewm-1.3.8 to 1.6.5 (2020-03-16).
I build it in /opt/icewm-1.6.5 as I usually do.

I have 
WorkspaceNames="1", "2", "3", "4", "5", "6"
~/.icewm/preferences file.

please see and compare:
this is OK view, the OLD 1.3.8 view: https://imgur.com/a/dHSMs7p
this is NOT OK view , the NEW 1.6.5 view: https://imgur.com/a/cvsTohk

The new look eats up A LOT of useful space on the new buttons with the names of the Workspaces which contains thumbnails/miniatures of opened applications that I don’t need.

digression and explanation why it is bad for me {
I usually open about 10 terminals at each workspace and I am greedy for a place in the taskbar (to see the titles of the terminals in the taskbar).
Also, I absolutely do NOT need to see thumbnails/miniatures of these terminals - they will looks the same!

these thumbnails/miniatures are not just useless - they obstruct,
I think for many other sys administrators working with the terminals, too.
And please do not advise me tabs in the terminals.
}

actually one question (splitted on three)--
how to switch to the old view (without thumbnails/miniatures of opened applications)?
how to remove\disable this miniatures of opened applications ?
How to make the Workspaces buttons names narrow as in 1.3.8 ?

**Comment by gijsbers** [comment]
You have two options with different effects:
1. change PagerShowPreview
2. change TaskBarWorkspacesLimit

**Comment by 5x3** [comment]
PagerShowPreview=0 what I need. I sure this will be useful to many. 
I really appreciate that you take into account usability in general and original Marko's IceWM appearance and keep optional all what related to original appearance !
You can count on my donation after self-isolation's ends.
IceWM best ever!
Thanks!
