### ISSUE TITLE
[Feature Request] MinimizeButtonShowsDesktop

### ISSUE THREAD

**Issue by developer1105** [ice-wm/icewm#140]
It would be interesting if IceWM had an option to minimize all windows when the user clicks the minimize button in any of the opened windows. As far as I know, no other WM has this feature and in my humble opinion it feels more natural and more intuitive, specially if you use lots of maximized windows. The default would be ```MinimizeButtonShowsDesktop = false```, and to activate this new feature it would be necessary to set ```MinimizeButtonShowsDestkop = true```.

**Comment by gijsbers** [comment]
It is not a good idea to grant every possible idea its own option, because the number of options would then explode tenfold. You can, however, easily define a key binding to accomplish this with the help of `icesh`.
