### ISSUE TITLE
More flexibility for WinMenuItems

### ISSUE THREAD

**Issue by developer1105** [ice-wm/icewm#143]
Under Preferences/String/WinMenuItems, there is a big string: ```rmsnxfhualytieckw```
This way it is possible to turn on/off almost any kind of thing that appears on WinMenu.
Unfortunately the thing I wanted the most: turn on ```maximize``` and turn off ```maximizeVert/maximizeHoriz``` is not possible yet.

My suggestion would be to include a letter g (g stands for grow [vertically or horizontally]) this way one could turn on/off these two items and leave ```maximize``` to be handled in an independent manner.
The new string would be, then: ```rmsnxGfhualytieckw``` (the g would be lowercase of course, I am just putting it here in uppercase so it would be more noticeable)

**Comment by gijsbers** [comment]
It would create an incompatibility with previous versions. It would need to be documented and communicated. People would need to spend time reading it, which is undesirable. The existing lettes refer to the menu accelerator. `g` doesn't. Hence it is a bad idea.
