### ISSUE TITLE
Incorrect menu interpretation? Bad $HOME or ~/ in menu option

### ISSUE THREAD

**Issue by cefer60** [ice-wm/icewm#146]
Debian 12
icewm 3.3.1
(I dont know is more new version have same "bug")

Try this:
echo "xxxxxxxx" >~/text

Then put this lines in .icewm/menu:

prog test1 noicon xterm -e nano ~/text
prog test2 noicon xterm -e nano $HOME/text
prog test3 noicon mousepad ~/text
prog test4 noicon mousepad $HOME/text

You can use geany or other editor

Only the first menu option (test1) work as expected

**Comment by gijsbers** [comment]
> options is the options and arguments passed to the program verbatim.

From https://ice-wm.org/man/icewm-menu#format. Please read the manpages!
