### ISSUE TITLE
Wayland

### ISSUE THREAD

**Issue by tim77** [ice-wm/icewm#147]
In 2024 mainstream DE's are discussing the possibility of completely switching to Wayland and drop the X11 session entirely ([GNOME](https://gitlab.gnome.org/GNOME/gnome-session/-/merge_requests/99), [KDE](https://pagure.io/fedora-workstation/issue/395)). Is there a chance that cute IceWM will be ported to Wayland one day?

**Comment by gijsbers** [comment]
bbidulock/icewm#70
