### ISSUE TITLE
How to vertically center the clock?

### ISSUE THREAD

**Issue by developer1105** [ice-wm/icewm#151]
It is possible to vertically center the clock with thin taskbars, and/or using the font 'sans' ...

But in other cases (different fonts, taller/thicker taskbar) it is not possible to get a vertically centered clock. 
It appears positioned at the top of the "clock-box", and there is an empty space below it.

**Comment by gijsbers** [comment]
Can you give examples of themes and screenshots of the problem?

**Comment by developer1105** [comment]
![window2](https://github.com/ice-wm/icewm/assets/67207296/458651b4-4a7f-4c71-825e-6154fb3bc362)

**Comment by gijsbers** [comment]
Names of the themes involved? Thanks!

**Comment by developer1105** [comment]
First Theme is BlueObscure:

ThemeDescription="BlueObscure IceWM"
ThemeAuthor="LuizFNunes"


Look=flat
TitleBarHeight=30
TitleBarJustify=50
TitleButtonsLeft="i"
TitleButtonsRight="xm"
TitleButtonsSupported="xmir"
BorderSizeX=4
BorderSizeY=4
#CornerSizeX=24
#CornerSizeY=16
DlgBorderSizeX=4
DlgBorderSizeY=4
RolloverButtonsSupported=1
MenuMouseTracking=1
TaskBarShowCollapseButton = 1
TaskBarGraphHeight = 36 # [16-1000]

#Icons
MenuIconSize=16
SmallIconSize=16
LargeIconSize=32
HugeIconSize=48

# Taskbar
TaskBarDoubleHeight=0
ShowAddressBar=0
TaskBarJustify="center"
TaskBarWidthPercentage=100
PagerShowMinimized=0
PagerShowBorders=0
TaskBarClockLeds=1

# Workspace
NormalWorkspaceFontNameXft="abel:size=12"
ActiveWorkspaceFontNameXft="abel:size=12"
ColorNormalWorkspaceButtonText="rgb:FF/FF/FF"
ColorActiveWorkspaceButtonText="rgb:1C/1B/20"

#Titlebar
ColorNormalBorder="rgb:3A/3E/42"
ColorActiveBorder="rgb:1C/1B/20"
ColorActiveTitleBar="rgb:1C/1B/20"
ColorNormalTitleBar="rgb:3A/3E/42"
ColorNormalTitleBarText="rgb:F0/F0/F0"
ColorActiveTitleBarText="rgb:FF/FF/FF"
TitleFontNameXft="abel:size=12:bold"

#Menu
ColorNormalMenu="rgb:1C/1B/20"
ColorActiveMenuItem="rgb:1C/1B/20"
ColorNormalMenuItemText="rgb:FF/FF/FF"
ColorActiveMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:25/24/29"
MenuFontNameXft="abel:size=13"


#Taskbar
ColorDefaultTaskBar="rgb:1C/1B/20"
ColorNormalTaskBarApp="rgb:1C/1B/20"
ColorNormalTaskBarAppText="rgb:FF/FF/FF"
ColorActiveTaskBarApp="rgb:3A/3E/42"
ColorActiveTaskBarAppText="rgb:05/D5/FC"
ColorMinimizedTaskBarApp="rgb:1C/1B/20"
ColorMinimizedTaskBarAppText="rgb:FF/FF/FF"
NormalTaskBarFontNameXft="abel:size=14:condensed"
ActiveTaskBarFontNameXft="abel:size=14:condensed"
TrayDrawBevel=0

#Listbox
ColorListBox="rgb:1C/1B/20"
ColorListBoxText="rgb:FF/FF/FF"
ColorListBoxSelection="rgb:05/D5/FC"
ColorListBoxSelectionText="rgb:FF/FF/FF"
ListBoxFontNameXft="abel:size=10"

#Scrollbar
ColorScrollBar="rgb:1C/1B/20"
ColorScrollBarSlider="rgb:3A/3E/42"
ColorScrollBarButton="rgb:3A/3E/42"
ColorScrollBarButtonArrow="rgb:FF/ff/ff"

#Move Size Status
ColorMoveSizeStatus="rgb:3A/3E/42"
ColorMoveSizeStatusText="rgb:FF/FF/FF"
StatusFontNameXft="abel:size=10:bold"


#QuickSwitch
ColorQuickSwitch="rgb:3A/3E/42"
QuickSwitchFontNameXft="abel:size=10"
ColorQuickSwitchText="rgb:FF/FF/FF"
ColorQuickSwitchActive="rgb:1C/1B/20"

#ToolTip
ColorToolTip="rgb:1C/1B/20"
ColorToolTipText="rgb:FF/FF/FF"
ToolTipFontNameXft="abel:size=13"

#Dialog
ColorDialog="rgb:FF/FF/FF"
ColorLabel="rgb:FF/FF/FF"
ColorLabelText="rgb:1C/1B/20"
ColorNormalButton="rgb:1C/1B/20"
ColorNormalButtonText="rgb:FF/FF/FF"
LabelFontNameXft="sans-serif:size=10"
NormalButtonFontNameXft="abel:size=14"
ActiveButtonFontNameXft="abel:size=14"
InputFontNameXft="abel:size=10"

#Desktop
DesktopBackgroundCenter=1
DesktopBackgroundScaled=1
DesktopBackgroundImage="default.png"

**Comment by developer1105** [comment]
```First theme is BlueObscure```

ThemeDescription="BlueObscure IceWM"
ThemeAuthor="LuizFNunes"


Look=flat
TitleBarHeight=30
TitleBarJustify=50
TitleButtonsLeft="i"
TitleButtonsRight="xm"
TitleButtonsSupported="xmir"
BorderSizeX=4
BorderSizeY=4
#CornerSizeX=24
#CornerSizeY=16
DlgBorderSizeX=4
DlgBorderSizeY=4
RolloverButtonsSupported=1
MenuMouseTracking=1
TaskBarShowCollapseButton = 1
TaskBarGraphHeight = 36 # [16-1000]

#Icons
MenuIconSize=16
SmallIconSize=16
LargeIconSize=32
HugeIconSize=48

#Taskbar
TaskBarDoubleHeight=0
ShowAddressBar=0
TaskBarJustify="center"
TaskBarWidthPercentage=100
PagerShowMinimized=0
PagerShowBorders=0
TaskBarClockLeds=1

#Workspace
NormalWorkspaceFontNameXft="abel:size=12"
ActiveWorkspaceFontNameXft="abel:size=12"
ColorNormalWorkspaceButtonText="rgb:FF/FF/FF"
ColorActiveWorkspaceButtonText="rgb:1C/1B/20"

#Titlebar
ColorNormalBorder="rgb:3A/3E/42"
ColorActiveBorder="rgb:1C/1B/20"
ColorActiveTitleBar="rgb:1C/1B/20"
ColorNormalTitleBar="rgb:3A/3E/42"
ColorNormalTitleBarText="rgb:F0/F0/F0"
ColorActiveTitleBarText="rgb:FF/FF/FF"
TitleFontNameXft="abel:size=12:bold"

#Menu
ColorNormalMenu="rgb:1C/1B/20"
ColorActiveMenuItem="rgb:1C/1B/20"
ColorNormalMenuItemText="rgb:FF/FF/FF"
ColorActiveMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:25/24/29"
MenuFontNameXft="abel:size=13"


#Taskbar
ColorDefaultTaskBar="rgb:1C/1B/20"
ColorNormalTaskBarApp="rgb:1C/1B/20"
ColorNormalTaskBarAppText="rgb:FF/FF/FF"
ColorActiveTaskBarApp="rgb:3A/3E/42"
ColorActiveTaskBarAppText="rgb:05/D5/FC"
ColorMinimizedTaskBarApp="rgb:1C/1B/20"
ColorMinimizedTaskBarAppText="rgb:FF/FF/FF"
NormalTaskBarFontNameXft="abel:size=14:condensed"
ActiveTaskBarFontNameXft="abel:size=14:condensed"
TrayDrawBevel=0

#Listbox
ColorListBox="rgb:1C/1B/20"
ColorListBoxText="rgb:FF/FF/FF"
ColorListBoxSelection="rgb:05/D5/FC"
ColorListBoxSelectionText="rgb:FF/FF/FF"
ListBoxFontNameXft="abel:size=10"

#Scrollbar
ColorScrollBar="rgb:1C/1B/20"
ColorScrollBarSlider="rgb:3A/3E/42"
ColorScrollBarButton="rgb:3A/3E/42"
ColorScrollBarButtonArrow="rgb:FF/ff/ff"

#Move Size Status
ColorMoveSizeStatus="rgb:3A/3E/42"
ColorMoveSizeStatusText="rgb:FF/FF/FF"
StatusFontNameXft="abel:size=10:bold"


#QuickSwitch
ColorQuickSwitch="rgb:3A/3E/42"
QuickSwitchFontNameXft="abel:size=10"
ColorQuickSwitchText="rgb:FF/FF/FF"
ColorQuickSwitchActive="rgb:1C/1B/20"

#ToolTip
ColorToolTip="rgb:1C/1B/20"
ColorToolTipText="rgb:FF/FF/FF"
ToolTipFontNameXft="abel:size=13"

#Dialog
ColorDialog="rgb:FF/FF/FF"
ColorLabel="rgb:FF/FF/FF"
ColorLabelText="rgb:1C/1B/20"
ColorNormalButton="rgb:1C/1B/20"
ColorNormalButtonText="rgb:FF/FF/FF"
LabelFontNameXft="sans-serif:size=10"
NormalButtonFontNameXft="abel:size=14"
ActiveButtonFontNameXft="abel:size=14"
InputFontNameXft="abel:size=10"

#Desktop
DesktopBackgroundCenter=1
DesktopBackgroundScaled=1
DesktopBackgroundImage="default.png"

**Comment by developer1105** [comment]
![window](https://github.com/ice-wm/icewm/assets/67207296/f2dac4a2-5d50-48f3-8679-7da25984adaa)

**Comment by developer1105** [comment]
```Second theme is yellowmotif```

ThemeDescription="Not too flashy, not too boring"
ThemeAuthor="Andreas Leitgeb <avl@logic.at>"

#Look=motif
#(warp3, warp4, win95; motif, nice, pixmap, metal, gtk)
Look=metal
TitleBarHeight=24
TitleButtonsSupported="xmis"
TitleBarHorzOffset=8 # -128-128
TaskBarGraphHeight = 34 # [16-1000]

BorderSizeX=4
BorderSizeY=4
CornerSizeX=22
CornerSizeY=22
DlgBorderSizeX=2
DlgBorderSizeY=2

#DesktopBackgroundImage=""
#DesktopBackgroundColor="rgb:40/a0/c0"

#ClockFontNameXft=sans:size=14
ClockFontNameXft=helvetica:size=12
#MenuFontNameXft="dejavusans:size=14"
MenuFontNameXft=sans-serif:size=14
NormalTaskBarFontNameXft="lucida:size=14"
ActiveTaskBarFontNameXft="lucida:size=14"

ColorNormalBorder="rgb:C0/C0/C0"
ColorActiveBorder="rgb:C0/C0/C0"
ColorNormalButton="rgb:C0/C0/C0"
ColorNormalTitleBar="rgb:C0/C0/C0"
ColorActiveTitleBar="rgb:FF/E7/00"
ColorNormalTitleBarText="rgb:00/00/00"
ColorActiveTitleBarText="rgb:00/00/00"
ColorNormalMenu="rgb:C0/C0/C0"
ColorActiveMenuItem="rgb:A0/A0/A0"
ColorNormalMenuItemText="rgb:00/00/00"
ColorActiveMenuItemText="rgb:00/00/00"
ColorDisabledMenuItemText="rgb:80/80/80"
ColorMoveSizeStatus="rgb:C0/C0/C0"
ColorMoveSizeStatusText="rgb:00/00/00"
ColorDefaultTaskBar="rgb:C0/C0/C0"
ColorNormalTaskBarApp="rgb:C0/C0/C0"
ColorNormalTaskBarAppText="rgb:00/00/00"
ColorActiveTaskBarApp="rgb:E0/E0/E0"
ColorActiveTaskBarAppText="rgb:00/00/00"
ColorMinimizedTaskBarApp="#C0C0C0"
ColorMinimizedTaskBarAppText="#000000"
ColorClock="#C0C0C0"
ColorClockText="#000000"

**Comment by developer1105** [comment]
![window2](https://github.com/ice-wm/icewm/assets/67207296/8f5b5afc-fd9e-4049-a213-d1a47bdc8747)

**Comment by gijsbers** [comment]
This change fixes it for me for the themes BlueObscure and yellowmotif.
Thanks for pointing this problem out.  I hope you enjoy this improvement.
