### ISSUE TITLE
KeySysTile per monitor?

### ISSUE THREAD

**Issue by schance995** [ice-wm/icewm#152]
I find the `KeySysTile` shortcuts useful for a single monitor setup. But on multi-monitor setups, all the visible windows will move to the monitor of the focused window.

Is it possible to tile only the windows on the focused monitor, leaving the windows on other monitors unchanged?

**Comment by gijsbers** [comment]
Not currently. IceWM was designed when multi-monitor setups were very rare, so this has to be added.

**Comment by gijsbers** [comment]
I made a change. If you want you can test it. See the attached diff.
[KeySysTile.txt](https://github.com/ice-wm/icewm/files/13538842/KeySysTile.txt)

**Comment by gijsbers** [comment]
This should fix the crash. Thanks for testing.
[KeySysTile.txt](https://github.com/ice-wm/icewm/files/13549317/KeySysTile.txt)
