### ISSUE TITLE
Tile Right Half on right monitor moves window to left monitor

### ISSUE THREAD

**Issue by schance995** [ice-wm/icewm#154]
On a dual monitor setup: [left|right]

Windows on monitor [right] move to the right side of monitor [left] when executing Tile Right Half, instead of moving to the right side of monitor [right].

**Comment by gijsbers** [comment]
There exists no "Tile Right Half".

**Comment by gijsbers** [comment]
Could you give the output of these two commands?
`xprop -root _NET_WORKAREA _NET_DESKTOP_GEOMETRY _NET_NUMBER_OF_DESKTOPS`
and `icesh xinerama`.

**Comment by gijsbers** [comment]
Can you maybe test this?
