### ISSUE TITLE
Browser small HTML element not clickable

### ISSUE THREAD

**Issue by allencch** [ice-wm/icewm#155]
Related to https://github.com/ice-wm/icewm/issues/62

OS: Arch Linux
Icewm version 3.4.4

Step to reproduce:

1. Open browser such as Firefox or even Brave, maximize the window
2. Visit website such as https://openinframap.org/
3. Open another window, also maximize
4. Do Alt-Tab to switch between the window.
5. On the browser, on the https://openinframap.org/ page, mouse over right-hand side layer icon, click the checkbox.
6. The checkbox not clickable

Workaround to resolve the issue,

7. Alt+LMB (left mouse button), we will be able to move the window, but no need move
8. Release Alt
9. Click the checkbox, now it is clickable.

**Comment by gijsbers** [comment]
Works fine here in version 3.4.5.

**Comment by allencch** [comment]
> Works fine here in version 3.4.5.

Thank you. I will try again once I updated to 3.4.5.

**Comment by allencch** [comment]
Tested with 3.4.5. It fixes the issue. :+1:
