### ISSUE TITLE
Dual-Monitor Support Broken, Ghosting Issue - Ubuntu 22.04.03 (VirtualBox 7.0.10 r158379)

### ISSUE THREAD

**Issue by VoxAndrews** [ice-wm/icewm#156]
### IceWM Version
Built from most current source code

### Description
When I try to set my monitors up in VirtualBox, I get this ghosting effect. I am using the xrandr command:

**xrandr --verbose --output Virtual2 --auto --primary --output Virtual1 --auto --left-of Virtual2**

As well as the Super+P pre-sets after using icewm-xrandr-menu, but it seems to cause this issue. Sometimes I've had it go away, but most of the time I get this ghosting issue from all of the windows and menus.

### Screenshot
![VirtualBox_Diet-Buntu - TESTING_29_01_2024_21_48_13](https://github.com/ice-wm/icewm/assets/26544407/5384057d-8e40-4c5a-82f7-9d2079251a05)

**Comment by gijsbers** [comment]
A window manager is about 2 tasks: window placement and input focus. Hence, this is not a problem due to icewm. Probably VirtualBox.

**Comment by VoxAndrews** [comment]
Ah my mistake, honestly still need to do some hardware testing as this is for a custom OS I'm working on. Thanks for the heads up though, appreciate it!

Also love IceWM, haha
