### ISSUE TITLE
Failure to restore focus in jedit and wine

### ISSUE THREAD

**Issue by cmbarry** [ice-wm/icewm#159]
icewm-1-4-BRANCH
jedit is a programmer's text editor written in java. 
If jedit has the focus when I switch to a different workspace then when I return to the original workspace then no windows appear active or have the keyboard focus. Clicking on the jedit title bar has no effect. Switching to a window not owned by jedit, then back again, either by using the mouse or Alt+Tab restores the focus, as does clicking on the jedit menu bar.
A similar loss of focus occurs when jedit closes one of its dialogs. For example, if I press ctrl+G to go to a specific line number then jedit will open a dialog to accept the line number. When the dialog closes then no window has the focus, just as in the case of switching workspace.
I first noticed this problem about two years ago. I tried the previous version of icewm, the previous version of jedit and various java runtimes. All with no affect. I tried other window managers, most of which, including fvwm, showed the same affect. However, fluxbox would restore the focus correctly, so I used that for a while.
Because I very much prefer icewm I recently decided to investigate the problem. Looking at the case of closing a dialog box I compared leafpad's search, where focus was restored correctly, with jedit's go to line. I found that execution diverged at line 1072 of wmmgr.cc, which contains:
if (f->getInputFocusHint() ||
In the leafpad case getInputFocusHint() returned true, but with jedit it returned false, so the entire condition evaluated to false. As an experiment I changed the line to:
if (true || f->getInputFocusHint() ||
so the result is always true. This seems to have cured the problem. I am using icewm with this modification now and have not noticed any adverse effects, but I have not tested it extensively.

**Comment by gijsbers** [comment]
Clearly looks like a bug in `jedit`. Why don't you report it there?

Icewm does have a bag of tricks to overcome application bugs.
In this case set the winoption `ignoreNoFocusHint` to `1`.

**Comment by cmbarry** [comment]
Because I get similar behaviour from wine. Specifically when running the circuit emulation program simetrix.
Furthermore, since jedit is written in java I would expect, although I have not looked at the source, that this would imply that the bug was in the java runtime, and, as I said, I have tried several different runtime versions.
I had used jedit for several years without any problems and this change in behaviour did not coincide with a change to jedit or to icewm so I would guess that that there was a change in X11 itself, but I do not know enough about that to know where to start looking.
I forgot to say in my initial post that I am using Arch Linux.

**Comment by gijsbers** [comment]
Can you verify that setting `jedit.ignoreNoFocusHint: 1` overcomes the first problem?

If you report that bug to the jedit developers then they can do something about it. If they conclude that they can fix their own code, that would be a win. If they conclude the bug is in Java, they can report it up to the Java developers. It is not up to you to decide what is the matter, since you are not the domain specialist.

Second. Your bug in wine may be similar or it may not. You don't know and you didn't do any detailed examinations. It is unclear what you are trying to achieve with this issue, since I can't fix jedit or wine.

You don't seem to be a seasoned software developer and that is just fine, but then give the relevant information to the people who are and who can do something about it and that is not here at icewm. Your reporting elsewhere may actually help others. Please do.

**Comment by cmbarry** [comment]
Firstly, I do not have easy access to other machines on which to test this,
so it may be truly unique to my own system. However, assuming that it is
reproducible:

1. After failing to restore activation and focus, none of the windows in
the workspace are active and the originally active window cannot be
activated or focused by clicking its title bar. I thought that you might
feel that icewm should never enter such a state, even in response to a
defective client.

2. jedit had worked for several years. As far as I can tell this behaviour
did not result from a change in jedit, the java runtime or icewm. Since it
seems that the problem can be cured by a minor change to icewm I thought
that you might be prepared to do that even though it did not arise from a
fault in icewm.

3. Setting "org-gjt-sp-jedit-jEdit.ignoreNoFocusHint: 1" provides a partial
cure. The window is now activated but not focused. However clicking inside
the window will give it the focus.

Since reporting this issue I have been using a version of icewm that has
been modified in the way I described. This seems to cure the problem
entirely, and so far I have not noticed any adverse effects, so from my
point of view the problem is solved. I reported it mainly because I thought
it might be useful to others.

**Comment by gijsbers** [comment]
`Jedit` advertises to the window manager a Globally Active focus model, which you can see from `icesh focusmodel`. Section 4.1.7 of the [ICCCM spec](http://www.x.org/docs/ICCCM/icccm.pdf) says:
`Thus, it wants to prevent the window manager from setting the input focus to any of its windows.`

IceWM honors that spec and the apparent wish of the application developers, even though they don't seem to be able to bear the responsibility of that design choice. Hence it is still desirable that you report to them. That would be much more "useful to others". Really. It is amazing to me that you refuse to do so.
