### ISSUE TITLE
APM battery status command (and memory status)

### ISSUE THREAD

**Issue by SweaterFish** [ice-wm/icewm#162]
IceWM's taskbar CPU status graph, network status graph, and mailbox status all have the ability to launch a command when clicked.

Unless I've missed it, there doesn't seem to be a similar option to run a command from the taskbar APM battery status. Nor for the memory status graph.

For consistency and additional usability, could these options be added? It seems it should be simple since the other status graphs already can do it.

Thanks and apologies in advance if this is already possible, but I just haven't found the preference.

**Comment by gijsbers** [comment]
It isn't yet possible. Consistency couldn't be a sufficient reason as it is non-functional (it doesn't do anything). Maybe someone argues next that everything should be clickable with a command for consistencies sake. Other WMs may be more consistent or more totally programmable? For "additional usability" it needs to be clear what useful command could be used on most platforms for a significant number of users.

**Comment by SweaterFish** [comment]
Maybe the default command could be

`watch cat /sys/class/power_supply/*/uevent`

That's available on all Linux systems that have a battery, I believe. As for useful, I really can't say whether it would be as useful to other people, but it certainly is to me.

**Comment by gijsbers** [comment]
That is very technical, specific to Linux and not a X11 application. Hence it doesn't meet the criteria.

**Comment by SweaterFish** [comment]
What are the criteria exactly? Earlier you just said useful and available on most platforms for a significant number of users.

The other default status commands also execute in a terminal and are pretty technical, aren't they?

Anyway, obviously you just don't want to do this, so nevermind. Enjoy your day.

**Comment by SweaterFish** [comment]
Oh well
