### ISSUE TITLE
double click border to resize window

### ISSUE THREAD

**Issue by ronaldklop** [ice-wm/icewm#163]
Hi,

On my MacOS machine I have a feature that double clicking the border of a window resizes that side of the window to the border of the screen. Kind of a maximize but only for one edge of the window. (The bottom edge stretches up to the menu.)
I found myself using this pretty often. I would love to have this on my FreeBSD+IceWM machine too.

Regards,
Ronald.

**Comment by gijsbers** [comment]
This looks acceptable if you can find more supporters. I hate single-user features.

**Comment by gijsbers** [comment]
Can you maybe test this to see if it is fully implemented?

**Comment by ronaldklop** [comment]
Thank you for implementing this feature and the really quick turnaround on the issue. I wanted to help testing, but didn't get to it before you already released a new version.
Now running 3.6.0 on my FreeBSD setup and it works really nice to resize the windows!
