### ISSUE TITLE
run dialog history is not saved

### ISSUE THREAD

**Issue by djshaji** [ice-wm/icewm#164]
Hi, as the title says. My run dialog history is not being saved. Whenever I open the run dialog it has no saved entries, and pressing up key does nothing. So I have to keep typing _google-chrome --force-device-scale-factor=1.6_ every time to launch my browser. 

Any help will be greatly appreciated. Thanks :+1: 

IceWM 3.4.7
Linux  6.9.0-0.rc3.20240411gite8c39d0f57f3.33.fc41.x86_64
Fedora release 41 (Rawhide)

**Comment by gijsbers** [comment]
What is the minimum number of history lines that need to be saved? 10?
For your favorite commands you can also make a toolbar entry, or a key binding, or a script.

**Comment by gijsbers** [comment]
A permanent history was implemented in commit bbidulock/icewm@e8015e8. Thanks for your suggestion.
