### ISSUE TITLE
The windows will be disordered when resize the screen

### ISSUE THREAD

**Issue by ElgebarOri** [ice-wm/icewm#165]
I‘m using icewm-3.4.7 on CentOS7, and I'm impressed with its simplicity and efficiency.

But lately I've noticed that when I change the screen size of a remote desktop session (IceWM running in the far end), the window order gets messed up, problem is the same with both NoMachine and VNC sessions.

Are there any setting options to avoid this problem from happening?

Screenshot gif attached shows this situation.

![动画](https://github.com/ice-wm/icewm/assets/36151397/df3b0e29-af95-460c-bda3-111e1bdc92bb)

**Comment by gijsbers** [comment]
The information you give is shallow and incomplete. Please be much more detailed.

1.  What do you mean precisely (in great detail) when you say "change the screen size"?
2. Do you make it greater or smaller or wider or taller or narrower? By how much precisely?
3. What do you mean precisely (in great detail) when you save "the window order gets messed up"?
4. I don't see a messed up window order in your screen dump.
5. Thanks for providing a screendump, but it would be much better to show the situation before and after.
6. Give different scenarios. Taller, wider, smaller, etc. Be detailed.
7. Include the output of `icesh -W this clients`.
8. What would you like the improvement to be?

**Comment by ElgebarOri** [comment]
I'm so sorry that I may not have been very clear in my previous statement.

I re-recorded a gif and try to describe the phenomenon I encountered as clearly as possible.

As the attached gif shows, I opened a Terminal and a gvim in a remote desktop session (IceWM running in the far end), this remote desktop utility is Exceed TurboX, and this virtual screen size can be adjusted by dragging and dropping with the mouse.

In this desktop session, terminal is maximized and gvim is not maximized, when I use mouse adjust the virtual screen size, the gvim window will always run to the top left corner,the relative positions of the various windows are disrupted, especially when there are a lot of windows, while other window managers, such as xfce4, will leave them in place. This happens no matter if I zoom in and out or lengthen and shorten or narrow and widen the virtual screen size.

Is there any way to keep the relative position of my windows at all times, no matter how I resize the dimensions of my virtual screen?

And when the window position changes, the output of `icesh -W 0 spy` is as follows:
```
01:13.351: 0x1c00003: Configure 0x1c00003 660x480+1+27 Send
01:13.354: 0x0600003: Configure 0x600003 1434x806+0+0
01:13.354: 0x0600003: Visibility PartiallyObscured 
01:13.354: 0x0600003: Visibility Unobscured 
```
My runtime environment is as follows:
CentOS7.9.2009 | IceWM-3.4.7 | Linux 3.10.0-1160.el7.x86_64

Thank you for your warm reply, best wishes!
![动画1](https://github.com/ice-wm/icewm/assets/36151397/7b23b441-988b-491f-be1f-ea6ee1cc7662)

**Comment by gijsbers** [comment]
This gif has frames with many different geometries and that makes it hard to understand.

Can you do something differently? Record the output of the commands at the same time:

1. `xev -root -event structure -event randr`
2. `icesh -r spy`

while you are resizing your virtual screen.

Is there no change in windows at all with xfce4 even when you make very small screen sizes?
Does xfce4 have configuration for what happens on screen dimension changes?

**Comment by ElgebarOri** [comment]
Hi, maybe I applied a theme so it makes this desktop look incomprehensible!

I changed to the default theme and re-recorded it.

In this record, I opened a gnome-terminal and a xclock, when I resize my virtual screen, the xclock run to the top left corner.

And here are output of：

1. `xev -root -event structure -event randr`

```bash
sunh@nxtest02[14:09] ~
>> xev -root -event structure -event randr

RRScreenChangeNotify event, serial 18, synthetic NO, window 0x2c5,
    root 0x2c5, timestamp 3022848878, config_timestamp 3022848878
    size_index 0, subpixel_order SubPixelUnknown
    rotation RR_Rotate_0
    width 1142, height 848, mwidth 290, mheight 215

RRNotify event, serial 18, synthetic NO, window 0x2c5,
    subtype XRRCrtcChangeNotifyEvent
    crtc 313, mode 1142x848, rotation RR_Rotate_0
    x 0, y 0, width 1142, height 848

RRNotify event, serial 18, synthetic NO, window 0x2c5,
    subtype XRROutputChangeNotifyEvent
    output screen, crtc 313, mode 1142x848 (1142x848)
    rotation RR_Rotate_0
    connection RR_Connected, subpixel_order SubPixelUnknown

ConfigureNotify event, serial 18, synthetic NO, window 0x2c5,
    event 0x2c5, window 0x2c5, (0,0), width 1142, height 848,
    border_width 0, above 0x0, override NO

ConfigureNotify event, serial 18, synthetic NO, window 0x2c5,
    event 0x2c5, window 0x2c5, (0,0), width 1142, height 848,
    border_width 0, above 0x0, override NO

ClientMessage event, serial 24, synthetic YES, window 0x2c5,
    message_type 0x1ad (_ICEWMBG_QUIT), format 32
```

2. `icesh -r spy`

```bash
sunh@nxtest02[14:09] ~/icewm/bin
>> ./icesh -r spy
10:07.092: 0x00002c5: RRScreenChange 0 order=0 rotation=0 width=1142px(290mm) height=848px(215mm)
10:07.092: 0x00002c5: RRCrtcChange crtc=313 mode=752 rotation=0 1142x848+0+0
10:07.092: 0x00002c5: RROutputChange output=314 crtc=313 mode=752 rotation=0 connection=RR_Connected subpixel=0
10:07.092: 0x00002c5: Configure 0x2c5 1142x848+0+0
10:07.092: 0x00002c5: Configure 0x2c5 1142x848+0+0
10:07.095: 0x00002c5: _NET_DESKTOP_GEOMETRY = 1142, 848
10:07.109: 0x00002c5: Configure 0xa00062 1142x1+0+847 Override Above=0xa00105
10:07.109: 0x00002c5: Configure 0xa00105 1142x51+0+797 Override Above=0xa07f61
10:07.109: 0x00002c5: _NET_WORKAREA = 0, 0, 1142, 797, 0, 0, 1142, 797, 0, 0, 1142, 797, 0, 0, 1142, 797, 0, 0, 1142, 797, 0, 0, 1142, 797
10:07.112: 0x00002c5: Configure 0xa07f61 382x377+0+0 Override Above=0xa001a1
10:07.112: 0x00002c5: Configure 0xa001a1 1149x799+-5+-5 Override Above=0xa00009
10:07.126: 0x00002c5: Send ClientMessage _ICEWMBG_QUIT 32 data=109595,0x0,0x0
10:07.128: 0x00002c5: _ICEWMBG_PID_S0 = 109595
10:07.241: 0x00002c5: _ICEWMBG_IMAGE = /tools/ctools/rh7.9/icewm/3.4.7/share/icewm/themes/default/default.png
10:07.243: 0x00002c5: _XROOTPMAP_ID(PIXMAP) = 23068674
10:07.244: 0x00002c5: _XROOTCOLOR_PIXEL = 0
10:09.668: 0x00002c5: Enter Normal Inferior Nofocus
10:09.678: 0x00002c5: Leave Normal Inferior Nofocus
```

In addition, I recorded another gif showing how xfce4 handles this situation.

Notice the xclock in the lower right corner, when the virtual screen size is large enough to display a portion of the xclock, it will remain in the same position, when the virtual screen size is reduced enough to display the xclock, it will move the xclock slightly to show a corner of the xclock, and when the virtual screen size is enlarged enough to accommodate the xclock, it will return to its original position. I'm using the default configuration of xfce4 without any additional settings for screen size changes.

Is there any configuration in icewm that makes it possible to not reposition windows when the virtual screen size changes?

Thank you very much!
![动画3](https://github.com/ice-wm/icewm/assets/36151397/e7cb346e-f2e3-4e41-aa10-f00d74070174)
![动画4](https://github.com/ice-wm/icewm/assets/36151397/d3dbf2be-8c15-4a4e-897f-63d5e5cc15a2)

**Comment by erikp121** [comment]
I "replicated" the window repositioning in a QEMU/KVM VM on icewm-session 3.4.7 (Fedora 40) by changing the resolution from 1920x1080 to 1680x1050 with xrandr. I do not know if it really is an issue take for example an extreme case of changing the resolution from 4k (3840x2160) to 640x480 with windows in each corner. What is the expected outcome? I would expect window repositioning and not windows outside of the screen/display?

Cheers.

**Comment by ElgebarOri** [comment]
> I "replicated" the window repositioning in a QEMU/KVM VM on icewm-session 3.4.7 (Fedora 40) by changing the resolution from 1920x1080 to 1680x1050 with xrandr. I do not know if it really is an issue take for example an extreme case of changing the resolution from 4k (3840x2160) to 640x480 with windows in each corner. What is the expected outcome? I would expect window repositioning and not windows outside of the screen/display?
> 
> Cheers.

However, in my daily use scenarios, I often encounter changes in the size of the virtual screen, such as when sharing a session using ETX Remote Desktop, and this size change is usually very small and I usually don't encounter the extreme situation you mentioned, but it causes my windows to rearrange, which can be confusing for me.

B&R

**Comment by gijsbers** [comment]
Thanks for all the detail. It is now clearer to me what you mean.
There is an option to turn the repositioning off.
It is has a clear name and it is documented in the manpage for icewm preferences.
An icewm installation comes with a full and up-to-date set of manpages.
If you type `man icewm-preferences` you should be able to scroll to ArrangeWindowsOnScreenSizeChange.
If you find anything unclear while reading the manpages you can always report it here.
If everybody would consult the manpages first before asking here that would help me so much.

**Comment by ElgebarOri** [comment]
> Thanks for all the detail. It is now clearer to me what you mean. There is an option to turn the repositioning off. It is has a clear name and it is documented in the manpage for icewm preferences. An icewm installation comes with a full and up-to-date set of manpages. If you type `man icewm-preferences` you should be able to scroll to ArrangeWindowsOnScreenSizeChange. If you find anything unclear while reading the manpages you can always report it here. If everybody would consult the manpages first before asking here that would help me so much.

Thank you very much for your answer, I'm sorry that `preferences` offers so many settings that I didn't read it carefully before, I searched some keywords in it but didn't find this option. I tried the method you provided and it did solve my problem, thanks again for your patience!

**Comment by erikp121** [comment]
> > Thanks for all the detail. It is now clearer to me what you mean. There is an option to turn the repositioning off. It is has a clear name and it is documented in the manpage for icewm preferences. An icewm installation comes with a full and up-to-date set of manpages. If you type `man icewm-preferences` you should be able to scroll to ArrangeWindowsOnScreenSizeChange. If you find anything unclear while reading the manpages you can always report it here. If everybody would consult the manpages first before asking here that would help me so much.
> 
> Thank you very much for your answer, I'm sorry that `preferences` offers so many settings that I didn't read it carefully before, I searched some keywords in it but didn't find this option. I tried the method you provided and it did solve my problem, thanks again for your patience!

Great that it worked out and that there were a setting for this special use case.

---

I tested ArrangeWindowsOnScreenSizeChange for my extreme (nut)case of changing resolution from high to low (1920x1080->640x480) and while initially the windows were "off-screen" (as expected) they automatically rearranges to the new screen size when (re)activated, i.e. minimzed and unminized or alt-tabbed.

I am like you very impressed by IceWM and it's customizability (there always seems to be an option). ArrangeWindowsOnScreenSizeChange seems "safe" even for extreme cases like I tried out.

Big shoutout to IceWM-developer(s)!
