### ISSUE TITLE
error while opening "si.1po" for reading: No such file or directory

### ISSUE THREAD

**Issue by sj-mx** [ice-wm/icewm#167]
During make of 3.5.0 on a funtoo system, the following error is generated:

> rm -f si.gmo && /usr/bin/msgmerge --for-msgfmt -o si.1po si.po icewm.pot && /usr/bin/gmsgfmt -c --statistics --verbose -o si.gmo si.1po && rm -f si.1po
/usr/bin/gmsgfmt: error while opening "si.1po" for reading: No such file or directory
make[3]: *** [Makefile:293: si.gmo] Error 1
make[3]: Leaving directory '/home/x/dev/icewm-3.5.0/po'
make[2]: *** [Makefile:336: stamp-po] Error 2
make[2]: Leaving directory '/home/x/dev/icewm-3.5.0/po'
make[1]: *** [Makefile:595: all-recursive] Error 1
make[1]: Leaving directory '/home/x/dev/icewm-3.5.0'
make: *** [Makefile:477: all] Error 2

I notice that
> msgmerge --for-msgfmt si.po icewm.pot

produces no output.

**Comment by gijsbers** [comment]
Do the following: cd to your icewm-3.5.0/po directory.
Then break down the make command in small steps and examine each output and exit code.
`/usr/bin/msgmerge --for-msgfmt -o si.1po si.po icewm.pot `
should produce an output file `s1.1po` on the basis of the si.po input file.
Check that previous similar commands succeeded. Why only the `si` language file?

**Comment by gijsbers** [comment]
Otherwise use the brute force `make -k` and see where that gets you.

Otherwise use the `rebuild.sh` script to use CMake as explained on the website or read the `INSTALL-cmakebuild.md` file.

**Comment by sj-mx** [comment]
@gijsbers note that I already broke the command down to:
> msgmerge --for-msgfmt si.po icewm.pot

Given that the output of `msgmerge` is what goes into `si.1po`
and no output is produced, I assume that there is an issue inside `si.po`.
In fact, after copying some other `.po` as `si.po` the make concluded successfully and now I am happily running `icewm` under funtoo.

Let me know if there is anything else that I can do to fix this.
And by the way, thanks so much for your hard work.

Cheers.
