### ISSUE TITLE
Creating shortcut with special characters: "/" 

### ISSUE THREAD

**Issue by reassuringgreet** [ice-wm/icewm#170]
Hi, I'm trying to create a shortcut with "Ctrl + Alt + /". I've tried to edit the keys file with "/", with "slash", but it doesn't seem to work. Is there any way to achieve this?

**Comment by gijsbers** [comment]
```
key "Alt+Ctrl+slash"    xterm
```
works for me. Did you reload with `icesh keys` and examine the output of icewm?

**Comment by reassuringgreet** [comment]
My bad, I had a typo in the command I was calling, sorry for the dumb question. Thanks for the help!
