### ISSUE TITLE
when building from source .....

### ISSUE THREAD

**Issue by develperbayman** [ice-wm/icewm#173]
so when i "./configure --prefix=/usr" it seems to make install in all the right directories /usr /share /bin ect  when i startx it kinda loads a partial terminal and is all frozen not sure how to get logs i have to hard reboot

**Comment by develperbayman** [comment]
issue#1
i could even use the older version but i cannot get ./icewm/startup/startup.sh to work when icewm loads i need it to automatically launch a python script 

i figured upgrading to the latest version would be the solution 

issue#2
also how to auto set a icewmbg permanently? one bg for all workspace is good enough for now  ...i followed the man pages from the web site i have even created a gui script that does it the issue is keeping the setting permanent 

if i can figure a few things out im going to do some really cool things

**Comment by gijsbers** [comment]
I do hope you start it with `icewm-session`.

It is `~/.icewm/startup`.

`icewmbg -f -p -i /path/to/your/image`

**Comment by develperbayman** [comment]
i did not? ....could you elaborate also i cannot get  ~/.icewm/startup to take (not for the icebg tho) i have a simple shell script to launch a python script but it fails to launch and my shell script is pretty basic 
```
#!/bin/bash

python3 /home/orangepi/pylinux/pypatriot.py "$@"

```

or does icewm/startup not support starting scripts? and i should be using like xinitrc?

**Comment by develperbayman** [comment]
> I do hope you start it with `icewm-session`.
> 
> It is `~/.icewm/startup`.
> 
> `icewmbg -f -p -i /path/to/your/image`

Startx icewm-session does not work x closes not even a messed up one but flat out closes

**Comment by develperbayman** [comment]
ran it again it worked ....not sure what happened ...how to close (make it never appear on load) xterm that auto loads and seems to kill icewm?  ....seems good!

**Comment by develperbayman** [comment]
that may be my fault  .ok thank you im going to mark this as closed
