### ISSUE TITLE
Always 1px black window border on right and bottom

### ISSUE THREAD

**Issue by fladd** [ice-wm/icewm#174]
It seems that all windows have a hardcoded black border at the right and bottom, when BorderSizeX and BoderSizeY are >= 1.

Using the "flat" look, I have both border sizes set to 1, and changing ColorNormalBorder or ColorActiveBorder will only affect the top and left borders (the resulting colour is actually also not exactly the one I specify, but a bit brighter one).

I don't seem to be able to set a 1 px border of the same colour around the entire window.

This issue also affects the QuickSwitch window, which, using the "flat" look, always shows this 1 px black border on the right and bottom, while not showing any border at all on the top and left.

Again, here I don't seem to be able to set a border of the same color around the entire window.

**Comment by gijsbers** [comment]
Can't repeat that here. Tried several `flat` themes. Most clear is theme `mimenum`.
How many themes did you try? No screenshots of right-bottom borders provided.
Please don't submit the same question twice. Geez.

**Comment by fladd** [comment]
First, I submitted this issue twice since there are two different GitHub repositories mentioned on the official ice-wm.org website, both with open issues, and it was not clear to me which is the official one.

Second, I realized this while creating my own theme. However, it is the same with other themes that use the flat style. While I could not find any theme called "mimenum" (I searched on themes.ice-wm.org), below is a screenshot showing the issue with the theme "LightBox" (https://www.box-look.org/p/1119109). I highlighted the problem with green (border present) and red (border not present) arrows.

![image](https://github.com/user-attachments/assets/de515853-6456-48a4-acde-d20df7476677)

@gijsbers Would you be able to reopen this issue again, given this new information?

**Comment by fladd** [comment]
And here is another example showcasing the same issue applied to window borders. For this I used the theme "shiceMavvert" (https://github.com/ice-wm/icewm-extra/tree/main/shiceMavvert) and simply changed `ColorActiveBorder` to magenta. Notice how the upper and left borders are now magenta, while the right and bottom ones are still black.

![image](https://github.com/user-attachments/assets/e917664d-719d-43a3-a5dc-d6dd9c7418a0)

**Comment by gijsbers** [comment]
This issue was never closed; only your duplicate one.

The `shiceMavvert` theme doesn't supply a set of frame pixmaps. Thus it defaults to black for the rightmost and bottommost frame border line. This has been deliberately the case since 2002:

```
^9de4b749 (gallium         2002-03-17 09:12:22 +0000 2437)                 g.fillRect
(1, 1, width() - 3, height() - 3);
^9de4b749 (gallium         2002-03-17 09:12:22 +0000 2438)                 g.drawBord
erW(0, 0, width() - 1, height() - 1, true);
```

An interesting test is increasing the border size to at least 5.

The theme  `mimenum` does supply frame border pixmaps.

**Comment by gijsbers** [comment]
Here is [mimenum](https://www.gnome-look.org/p/1166710).

**Comment by fladd** [comment]
I think the issue is indeed less problematic for window borders, as you can use frame border pixmaps to achieve a uniform 1px frame I guess.

My question is more why this is the default when not using frame border pixmaps though. While this makes sense for 3D designs (as having a border on the bottom left only will give you this raised relief effect), I doesn't really seem to make sense for flat designs.

And since the QuickSwitch window does not seem to use these frame border pixmaps, there currently seems to be no way to make the QuickSwitch window have a 1px uniform frame, right?

**Comment by gijsbers** [comment]
The `Why` question can be asked thousands of times, but the original authors are no longer around to answer them. It is like it is.

**Comment by fladd** [comment]
Okay, so no fix for the QuickSwitch either?

**Comment by gijsbers** [comment]
I'm not convinced. It's the way it always has been. If you don't like it, use another Look. Also, it seems that running `picom` makes it go away.

**Comment by gijsbers** [comment]
This should fix it for the QuickSwitch.

**Comment by fladd** [comment]
Thanks @gijsbers for this fix. I understand that this removes the current 1px border making the QuickSwitch always borderless. Will there also be a way to set a uniform frame around the QuickSwitch window?

**Comment by fladd** [comment]
@gijsbers Thanks for adding the option to set the window border color for the QuickSwitch. As far as I understand, this will always add a 1 px border in that color, right? Could the size of this color potentially be changed as well (e.g. 2 or 3 pixels if one wants?). Also, I see that you reverted the fix for the 1px border right and bottom. This is really a pity since this means even when setting ColorQuickSwitchBorder, one will have a 1px border left and top, but a 2 px border bottom and right. Unless I am missing something. So I would consider this issue not fixed at the moment.

**Comment by gijsbers** [comment]
The border size is unchangeable. That code is too hairy.

Take for instance the distinction between QuickSwitchVertMargin and QuickSwitchIconMargin. If you can figure that one out be my guest.
