### ISSUE TITLE
not working keyboard after screen is unlocked

### ISSUE THREAD

**Issue by mkdruss** [ice-wm/icewm#177]
Hello,
after upgrade icewm from 2.1.2-1 to 3.3.1-1 (debian), keyboard not working (like disconnected) after screen is unlocked. I must click mouse to another window than last active window or next workspace. Keyboard then works again.

I tested
LockCommand="i3lock"
and
LockCommand="xsecurelock"
simple without arguments. 

If I run any lock command manually or via hotkey
key "Alt+Ctrl+x"                i3lock
#key "Alt+Ctrl+x"               xsecurelock
keyboard works after unlock.

**Comment by gijsbers** [comment]
In the first case (not manually and not via hotkey) at the top of your issue, how is the screen locked?

**Comment by mkdruss** [comment]
Moment, new information, keyboard stop working after displaying menu with "lock workstation",  "reboot", "shutdown", etc. After ctr+alt+del and then key ESC. No lock is needed.

In this menu keyboard works, after lock or pushing ESC keyboard stop working.

**Comment by mkdruss** [comment]
I tried to delete ~/.icewm/ and restart icewm,
same problem with default config

**Comment by gijsbers** [comment]
This may be specific to `version 3.3.1`. I can indeed reproduce something like this with `3.3.1`.
With the current version `3.6.0` it works fine. `3.3.1` is 21 months old.

**Comment by mkdruss** [comment]
omg, I forgot that stable debian often has not fresh software. Sorry and thanks for your quick help.
