### ISSUE TITLE
<ctrl><alt><left/right arrow> don't work anymore

### ISSUE THREAD

**Issue by HJarausch** [ice-wm/icewm#180]
Upto until recently the keyboard actions  <ctrl><alt><right or left arrow> have worked just fine.
But now these keys don't work anymore.

I am on Gentoo Linux running x11-base/xorg-server-21.1.15 and icewm-3.6.0

What could have changed?  How to fix it?

Thanks,
Helmut

**Comment by gijsbers** [comment]
Dunno. A computer system is incredibly complex. We don't provide a free service to help maintain people's computers.
