### ISSUE TITLE
graphical keyboard layout switcher to use with IceWM

### ISSUE THREAD

**Issue by 5x3** [ice-wm/icewm#20]
I used qxkb app from Fedora packages but after upgrade to new Fedora version qxkb starts but failed to change laytout.
It resides in tray area (around clock) and have graphical key (flag) to click to change layout also it is shows current laytout,
both functions are broken in new Fedora OS.

Can you please suggest what I can use for IceWM with similar functionality.

Thanks in advance.!

**Comment by gijsbers** [comment]
CC disels/qxkb#7. It is also broken in Fedora 32 for qxkb-0.5.1-1.fc32.x86_64.
The first time it shows the configuration window, but then it just hangs.
The first time it does show an icon in the icewm systray, but not subsequently.

You can consult the Arch wiki for similar programs: 
https://wiki.archlinux.org/index.php/List_of_applications/Utilities#Keyboard_layout_switchers

**Comment by 5x3** [comment]
gxneur is only working solution but it mostly looks like keylogger than switcher - it collects all inputs and interfere - very insecure.

Can you please consider to introduce icewm native switcher?

It can be even without bitmap country flags representation but just capitalized layout names like "US" on click it just change to the next layout, as simple as possible but working. Also if you decide to introduce it - please make it optional, so I can enable it or disable.

thanks!

**Comment by gijsbers** [comment]
Implemented by commit 468f75e5547496e534e4ae2ab65a31b6b5a47730.
