### ISSUE TITLE
[Possible bug] Problem with dosbox and re-maximize the screen

### ISSUE THREAD

**Issue by rubyFeedback** [ice-wm/icewm#21]
Hey there,

I can go into dosbox playing master of orion 1 :-)

But upon quitting it via "alt + F4", I get a minimized screen.

This looks strange ... so perhaps a screenshot:

https://i.imgur.com/WgSUC3X.png

In case it is not obvious, the menu pane on the bottom is
now suddenly in the ~middle and I can not move it.

This only happens with dosbo so far.

I still have full screen control though because other applications I can maximize
to the full size screen. Just the pane of icewm stays as it is.

I have no idea how this is caused internally - perhaps I may have
some old xorg-libs, although I think I upgraded all of them to the
latest. Perhaps icewm tries to determine the old position but does
not determine the correct one. A work around might be if we could
manually drag the bottom pane, or perhaps some action that
lets the bottom icewm pane re-align.

I used to use fluxbox in the past but changed to icewm for several
reasons. :)

**Comment by gijsbers** [comment]
Which version of IceWM? Which operating system version?
How do you start the command? What files do I need?
What steps do I need to do exactly precisely in detail to repeat on my machine what you got?
