### ISSUE TITLE
strtok_r() usage in src/misc.cc may lead to infinite loop

### ISSUE THREAD

**Issue by danfe** [ice-wm/icewm#23]
The following loop can go wrong on some systems because it assumes that `save` may not become zero again, which is not guaranteed, and may in turn lead to an infinite loop:
```c
    while ((directory = strtok_r(save ? 0 : env, ":", &save)) != 0) {
            // we might never get out of here...
    }
```
Correct way is to separate the calls and `directory` check.  Compare to the similar loop in the `src/yicon.cc` for example:
```c
    for (char *tok = strtok_r(copy, ":", &save);
        tok != 0; tok = strtok_r(0, ":", &save)) {
            // here, we have a chance to catch out-of-tokens condition
    }
```
[Here](https://svnweb.freebsd.org/ports/head/x11-wm/icewm/files/patch-src_misc.cc) is the actual patch.

**Comment by gijsbers** [comment]
This affects FreeBSD, NetBSD and OpenBSD. Glibc based systems should be fine.

**Comment by danfe** [comment]
Yeah, it mainly affects *BSD systems, however, the underlying assumption, and thus the `while()`-only code, is still wrong.  Thanks for fixing.
