### ISSUE TITLE
Some fullscreen windows (mostly games) minimize when unfocused

### ISSUE THREAD

**Issue by Brottweiler** [ice-wm/icewm#24]
Usually this happens when I switch to another workspace. My fullscreen game, for example Minecraft in this case, will be minimized when I switch back to the workspace it is on. This also happens when alt+tabbing to another window.

This does not happen with all games, however. Only some, but Minecraft is such a game that will always get minimized when I switch workspace or window. I never had this issue when using Openbox, and as I said, only some games seem to be affected.

I am using IceWM 1.8.

**Comment by gijsbers** [comment]
How to repeat your scenario? What software do you use to run your games? What are the commands that starts them? Is there some simple easily downloadable game which does it (sometimes)?

**Comment by Brottweiler** [comment]
A free game I tried now that this happens with is OpenTTD. Switching to another workspace and back, the game is minimized. I can start that game by just running `openttd` in the terminal. I am on Archlinux and OpenTTD is installed from the main repos. 

Are you able to reproduce this with OpenTTD? for example? I'll see if I can find some other free games to test with.

**Comment by Brottweiler** [comment]
This also happens with Teeworlds. You can find it on

**Comment by gijsbers** [comment]
I installed minecraft, and the startup screens work, they allow to continue without login, but to play I need to sign up, which I prefer to avoid. 
I could play openttd and all seems fine no matter what I try.
For Teeworlds I need Steam, which requires lots of dependencies I don't want.
Maybe you can do a `icesh spy` on the window which is misbehaving or `sleep 3; icesh -c minecraft spy` or whatever, see icesh(1). Delay a bit when switching workspaces to get a clear time difference in the output.

**Comment by Brottweiler** [comment]
```
46:27.083: 0x3600007: Leave Grab Ancestor Nofocus
46:27.083: 0x3600007: _NET_WM_STATE = _NET_WM_STATE_FOCUSED
46:27.112: 0x3600007: Focus Normal Nonlinear
46:27.112: 0x3600007: Enter Ungrab Ancestor Focus
46:28.769: 0x3600007: WM_NORMAL_HINTS
46:28.789: 0x3600007: _NET_WM_BYPASS_COMPOSITOR(CARDINAL) = 1
46:28.789: 0x3600007: _NET_WM_FULLSCREEN_MONITORS(CARDINAL) = 0, 0, 0, 0
46:28.794: 0x3600007: _NET_WM_STATE = _NET_WM_STATE_FOCUSED, _NET_WM_STATE_FULLSCREEN
46:28.794: 0x3600007: _WIN_LAYER(CARDINAL) = 14
46:28.794: 0x3600007: Configure 1920x1080+0+0
46:28.794: 0x3600007: Visibility PartiallyObscured
46:28.794: 0x3600007: Visibility Unobscured
46:28.794: 0x3600007: Configure 1920x1080+0+0 Send
46:28.794: 0x3600007: _NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
46:28.795: 0x3600007: Visibility FullyObscured
46:28.795: 0x3600007: Visibility Unobscured
46:31.195: 0x3600007: Defocus Grab Ancestor
46:31.198: 0x3600007: Defocus WhileGrabbed Nonlinear
46:31.226: 0x3600007: Leave Normal Nonlinear Nofocus
46:31.238: 0x3600007: Unmap
46:31.238: 0x3600007: _NET_WM_STATE = _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN
46:31.243: 0x3600007: _WIN_LAYER(CARDINAL) = 4
46:31.244: 0x3600007: _WIN_STATE(CARDINAL) = 2, 1023
46:31.244: 0x3600007: _NET_WM_STATE = _NET_WM_STATE_HIDDEN, _NET_WM_STATE_FULLSCREEN
46:31.244: 0x3600007: WM_STATE(WM_STATE) = 3, 0
```
I had minecraft open in windowed mode, ran `icesh spy` and clicked on it. then I did this order
1. clicked to select the winecraft window
2. pressed F11 to fullscreen
3. switched to another workspace
4. switched back to the workspace with minecraft on it
5. ctrl+c to quit `icesh`.

Is that log above useful?

**Comment by Brottweiler** [comment]
About Teeworlds, you can play it outside of Steam. You might be able to install it from your package manager. https://www.teeworlds.com/?page=downloads

**Comment by gijsbers** [comment]
I can repeat your scenario with Teeworlds. When I run icewm with even logging enabled (this is a configure option --enable-logevents, which also requires either a preferences setting Logevents=1 or the --logevents command line option), then I can see that Teeworlds sends an iconify request to the window manager. It looks like this:

    IceWM: window=0x400011: clientMessage WM_CHANGE_STATE fmt=32 data=3,0x0,0x0

Its X11 call is documented here: 
https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/XIconifyWindow.html

Icewm simply obeys the request of Teeworlds to be iconified. No bug.
If you want you could enable event logging and see if the other programs send similar requests.

**Comment by Brottweiler** [comment]
Ah! Very interesting. I suppose other games, like Minecraft, also does this then. I thought this might have been a bug somehow because games did not iconify on Openbox, but maybe _that_ was a bug in Openbox.

I will make sure and see if Minecraft also sends an iconify request. If I enable `LogEvents`, where can I read the log afterwards?

**Comment by gijsbers** [comment]
I don't know. It depends on the system. You run Arch, right? You run a display manager like SLiM or GDM? Check their docs or search for that. If you start your window manager from ~/.xinitrc or ~/.xsessionrc, which I do, then you can set it there.
Maybe you can modify the icewm-session.desktop somehow to redirect output, dunno, search.

**Comment by Brottweiler** [comment]
I tried setting `exec icewm-session --enable-logevents` but it says `icewm-session: Warning: Unknown option '--enable-logevents'` 😕

As for logging, I figured it out by doing `startx &> ~/startx.log`.

**Comment by gijsbers** [comment]
You can check that it was configured with logevents enabled by `icewm --configured`. It should print logevents in the output:

    icewm configured options: alsa ao fdomenus fribidi gdkpixbuf i18n librsvg libxpm logevents nls oss session shape xfreetype2 xinerama xrandr

(@Code7R Strangely, the CMake build doesn't seem to support this option?)

**Comment by Brottweiler** [comment]
I have this in my config
```
#  Enable event logging for debugging
LogEvents=1 # 0/1
```
but it doesn't seem to be enabled `icewm configured options: alsa ao fdomenus fribidi gdkpixbuf i18n librsvg libxpm nls oss session shape xfreetype2 xinerama xrandr`

I did try to also use the `--logevents` cmd line option but doesn't seem to work either `icewm-session: Warning: Unknown option '--logevents'`.

**Comment by gijsbers** [comment]
By default icewm does not have it in the executable to save some space. That is why it complains it doesn't understand the option. To get it the `configure` must be told to include it. Do `./configure --help=short` and examine the output. Then you should see:

   --enable-logevents      Support logging of X11 events.

Then `./configure --enable-logevents ............ (whatever else you may want)` should do the trick. Then make and make install.

**Comment by gijsbers** [comment]
Ah now I see. You give the option to `icewm-session`. But it can only be given to icewm. Don't give it to `icewm-session` and just set it in the preferences.

**Comment by Brottweiler** [comment]
I'm going to close this as this is probably intended behaviour, like how you explained that Teeworlds sent an iconify request. Configuring and recompiling IceWM is a bit too much of a bother for me right now.

Thanks for the support!
