### ISSUE TITLE
Question: taskbar workspaces buttons

### ISSUE THREAD

**Issue by Eli-the-Bearded** [ice-wm/icewm#27]
I'm unclear how to configure the taskbar workspace buttons. With an older version of icewm, they just showed up as rectangles with numbers in them. Since I upgraded from 1.3.7 the buttons show up with rectangles on them representing the windows on each workspace. I find this looks cluttered. Futzing around I managed to get the buttons completely blank, which is better but not as good as numbered. What preference name do I want to change?

**Comment by gijsbers** [comment]
It's called `PagerShowPreview`. https://ice-wm.org/man/icewm-preferences

**Comment by Eli-the-Bearded** [comment]
Yeah, that get's me completely blank. I see it is apparently a "feature" that you can't have numbers without the previews:


```
PagerShowNumbers=1

Show number of workspace on workspace button (if PagerShowPreview=1).
```

The documentation, by the way, could really be helped with some screenshots. I didn't know the workspace switcher was called the "pager" and was mostly looking at taskbar options.

**Comment by gijsbers** [comment]
If PagerShowNumbers=0 then you should see your workspace names on the buttons.
I agree screenshots in the documentation would be nice, but these are manpages and manpages are text only.
You don't give any screenshots for your own observations...
"Pager" is standard terminology for WMs. See http://rox.sourceforge.net/desktop/Pager.html and https://specifications.freedesktop.org/wm-spec/latest/.
