### ISSUE TITLE
taskbar autoraise is broken sometime

### ISSUE THREAD

**Issue by boycottsystemd** [ice-wm/icewm#29]
It tooks few seconds sometime - much more than specified. 
It did not autoraise in 10 seconds sometime (I've stopped testing/waiting after 10 seconds.)

Fedora 31, kernel 5.8.16-100.fc31.x86_64

I don't know how to reproduce it.

TaskBarAutoHide=1
AutoHideDelay=3
AutoRaiseDelay=0
AutoShowDelay=0

**Comment by boycottsystemd** [comment]
icewm-1.9.0-1.fc31 
(Edit does not work)

**Comment by gijsbers** [comment]
Thanks for reporting this. I fail to reproduce it sofar. We need reproducability.
You could test by setting AutoHideDelay and/or AutoShowDelay to 50 milliseconds.
AutoRaiseDelay is not relevant.

**Comment by boycottsystemd** [comment]
You are welcome. I'm sorry I couldn't reproduce it.
