### ISSUE TITLE
DesktopBackgroundScaled not scaling png properly

### ISSUE THREAD

**Issue by RobChrystie** [ice-wm/icewm#3]
We have a 1000X730 png that we use for the background image. We want it to fit full screen. In the previous version (1.3.8) we were able to set DesktopBackgroundScaled=1 and the background image would display full screen properly. In the current version (1.5.3) the background is stretched and seems to fit more then the screen (sort of zoomed in)

**Comment by gijsbers** [comment]
This is explained in the icewmbg man page in the section named SCALING.

**Comment by Code7R** [comment]
@RobChrystie Do you still see a problem here? If not, please close this ticket.
