### ISSUE TITLE
configure fails with gdk-pixbuf-2.42

### ISSUE THREAD

**Issue by HJarausch** [ice-wm/icewm#31]
I am on Gentoo Linux. The recent gdk-pixbuf-2.42 installs /usr/lib64/libgdk_pixbuf-2.0.so but
configure cannot find it. Is there a fix for configure.ac ?
Thanks,
Helmut

**Comment by gijsbers** [comment]
Hello Helmut
The icewm distribution provides a script called rebuild.sh.
Could you run it like this: `./rebuild.sh -d`
This should give you a list of all the required icewm dependencies
which can be found on your system. Specifically, it executes:
`pkg-config --modversion --print-errors --errors-to-stdout gdk-pixbuf-xlib-2.0`
This may actually be a problem with gdk-pixbuf for your system
and you could contact that maintainer to ask what has changed?

**Comment by gijsbers** [comment]
See bbidulock/icewm#513.
