### ISSUE TITLE
AddressBar completion?

### ISSUE THREAD

**Issue by fladd** [ice-wm/icewm#33]
The documentation says that the AddressBar supports completion with either "Tab" or "Ctrl-I". This does not seem to work, or it is not clear how it should work.

For instance, I type "python my_script." and then hit "Tab", assuming that this will complete to "python my_script.py", but nothing happens.

How exactly is the completion supposed to work, and how does one set it up correctly?

**Comment by Code7R** [comment]
It will complete the first world by looking at the executable in $PATH. It will not complete the arguments, and especially not in a smart way like bash-completion.

**Comment by fladd** [comment]
Thanks for the clarification.

It appears that the documentation is misworded then, because it states explicitly that the AddressBar supports "file completion" (and "my_script.py" in my example is a file of course).

Also, even completing executables still seems to work quite inconsistently here (using Antix 19.3):
E.g. typing "py" and then hitting TAB will not do anything. "pyt" will complete to "python".
Typing "fir" will expand to "fire" (which does not exist).

**Comment by Code7R** [comment]
It completes to the shortest common prefix. I guess you have at least a couple of tools which names start with fire. The little drawback here compared to a common shell is that you don't get a visual or audible notification that the shown prefix is not complete.

**Comment by fladd** [comment]
I see. Thanks for the explanation. In that case, let's consider this a feature request:
Full shell-like completion

:-)

**Comment by DarkSamus669** [comment]
I would recommend everyone to use [dmenu](https://tools.suckless.org/dmenu/) or [rofi](https://github.com/davatorium/rofi).

**Comment by gijsbers** [comment]
This adds completion to the last argument. If there is more than one match, it expands to the common prefix. Let me know if this is enough.
