### ISSUE TITLE
Question: what happened with Iconize menu item?

### ISSUE THREAD

**Issue by exebook** [ice-wm/icewm#37]
The iconize menu item was awailable when you right click the task bar entry it was removing the application from the task bar and instead add it to the tray as an icon. After I updated from github the menu item disappeared. What happened? Can I get it back by some config option or compilatin option?

**Comment by gijsbers** [comment]
What does your menu now look like?

**Comment by exebook** [comment]
![Menu_049](https://user-images.githubusercontent.com/3821217/103045180-11cdda80-45b6-11eb-8a85-53f129a8c8a8.png)

**Comment by gijsbers** [comment]
What was your previous version where it still worked for you?
The menu can have a "Tray _icon" entry below the "Occupy _All".
This is missing in your menu. Two conditions must be met. Do:
```
icewm --postpreferences | grep -e WinMenuItems -e TaskBarShowTray
```
Check that WinMenuItems contains an `i`. TaskBarShowTray must be 1.

**Comment by exebook** [comment]
I had `TaskBarShowTray=0`, with `1` it works, thank you very much. You're my hero!
