### ISSUE TITLE
How to get latest by git pull?

### ISSUE THREAD

**Issue by gnusupport** [ice-wm/icewm#38]
I just did git pull and in the NEWS I can see only this:

```
icewm -- history of user-visible changes.  2020-10-29

Release icewm-1.9.0 released 2020-10-29
```

but not anything related to version 2.0

what do I need to do to get to 2.0? Is it new branch?

**Comment by gijsbers** [comment]
Check the output of `cat .git/config`. To which repo does it point?
Can you follow the instructions on https://ice-wm.org/?

**Comment by gnusupport** [comment]
* gijsbers <notifications@github.com> [2020-12-24 16:49]:
> Check the output of `cat .git/config`. To which repo does it point?
> Can you follow the instructions on https://ice-wm.org/?

As I had git repo from before, simple `git pull` did not work.

Then I have used rsync to get newest version from my server, and I
could pull it to have version 2.0.

Please close the bug.
