### ISSUE TITLE
Allow using Win95 keys for standalone keybinding

### ISSUE THREAD

**Issue by exebook** [ice-wm/icewm#39]
There are WIN, START, MENU keys, those you know located somewhere between the ALT and CONTROL keys, they are named differently and have idfferent icons on various keyboars. They are super common like I barely ever see a (non Mac) keyboard without those. I love to bind certain actions to those because they are very close to my fingers, esp. switching between last two windows and zooming the current window. The problem is that IceWM does not allow that! I have to apply my own patch each time I update. The IceWM seem to treat those keys like modifier keys that can only be used to accompany some other "real" keys. But I do not care to use them as modifiers I just want them as a standalone keys. That is my feature request please.

I would not PR my "patch" because it basically deletes and comments out some useful for others code in some ugly and obviously wrong way, I do not even understand how it actually works I just hacked for a few hours (days actually) until I got it somewhat doing what I want. I recall it had `if (win95) {` clauses in the places of interest.

**Comment by gijsbers** [comment]
IceWM already binds those keys for various actions.
They are `Multi_key, Menu, Super_R`.
You can get details on them with `xev`.
Maybe run `xev` under a dedicated `Xephyr`.
Using `xmodmap` you could reassign them to something else.
