### ISSUE TITLE
Impossible to do automatic merge icewm-1-4-BRANCH into master

### ISSUE THREAD

**Issue by jinn-alt** [ice-wm/icewm#42]
Hello!
What happened to the git-repository? Impossible to do automatic merge icewm-1-4-BRANCH into master.
I wanted to do `git merge 2.1.1` into master so that all tags are in the same branch, but there are multiple conflicts and automatic merge is not possible.
Is it possible to do something about it, otherwise it became impossible to use the repository. And this is ugly, as it spoils the structure of the repository.

**Comment by gijsbers** [comment]
Please try again.

**Comment by jinn-alt** [comment]
Thank you very much for your work, colleague.
Now everything is OK.
