### ISSUE TITLE
icewm does not recognise custom xpm mouse files

### ISSUE THREAD

**Issue by clemencyworld1** [ice-wm/icewm#45]
It was working before but after a reinstall i could not use my themed cursor files again. The ones I downloaded from the net works but the ones I created in gimp do not work any longer.

Running icewm from terminal using my configured theme gives this error:

_**IceWM: Warning: Invalid cursor pixmap: "/home/clemency/.icewm/themes/22oz/cursors/left.xpm" contains too many unique colors
IceWM: Unknown keyword for a non-container: 'Win95Keys'.
Expected either 'key' or 'runonce' here.
IceWM: A window manager is already running, use --replace to replace it_
[cursors.zip](https://github.com/ice-wm/icewm/files/6227047/cursors.zip)

**_

I have tried removing all colours from the cursor files but still do not work.
i don't know how to create cursor files that can be recognised by icewm. But it worked before.

The cursor files I created are attached

**Comment by clemencyworld1** [comment]
Sorry i attached the wrong files. I will update it soon

**Comment by gijsbers** [comment]
At the moment the XPM based support for cursors only accepts mono cursors.
That is like two-colors black and white. But you can disable the XPM support
by editing config.h like follows and then recompile and reinstall and restart:
```
$ grep -i -e xpm -e imlib config.h
/* Define to enable imlib2 rendering. */
#define CONFIG_IMLIB2 1
/* Define to enable libxpm rendering. */
/* #define CONFIG_XPM 1 */
```
Then your beautiful colored cursors will work.

**Comment by clemencyworld1** [comment]
i installed debian version over github version and its now working. Probably i missed something during compilation. do not know what i missed.

#Debian verion alone did not give me icesound and icewmbg.

**Comment by clemencyworld1** [comment]
> At the moment the XPM based support for cursors only accepts mono cursors.
> That is like two-colors black and white. But you can disable the XPM support
> by editing config.h like follows and then recompile and reinstall and restart:
> 
> ```
> $ grep -i -e xpm -e imlib config.h
> /* Define to enable imlib2 rendering. */
> #define CONFIG_IMLIB2 1
> /* Define to enable libxpm rendering. */
> /* #define CONFIG_XPM 1 */
> ```
> 
> Then your beautiful colored cursors will work.

Ok. I will try that

**Comment by gijsbers** [comment]
You also need to define the `hotspot` in your cursor images.
That is the sensitive spot of your cursor and the center of action.
How to do that is explained in https://en.wikipedia.org/wiki/X_PixMap#XPM3.

**Comment by clemencyworld1** [comment]
Yes, the cursors now show but still looks mono coloured. I think I can manage that.
Thanks

**Comment by clemencyworld1** [comment]
Thanks a lot. Am working on it now
