### ISSUE TITLE
How to build all the html man pages using the CMake build?

### ISSUE THREAD

**Issue by realsimix** [ice-wm/icewm#50]
With the classic make I was able to build the man pages as html with the `docDATA` target.

Unfortunately I was unable to find out how to achieve the same with CMake?

Any help would be much appreciated!
Regards,
Simon

**Comment by gijsbers** [comment]
There is no such support yet in the CMake build yet, sorry.
The primary build system is configure + make.

**Comment by gijsbers** [comment]
You can test if this works for you too.

**Comment by realsimix** [comment]
Thank you very much, works wonderfully!
