### ISSUE TITLE
Certain menus don't work right when chrome is in the Normal Layer

### ISSUE THREAD

**Issue by jidanni** [ice-wm/icewm#62]
Certain menus don't work right when chrome is in the Normal Layer.
If one makes chrome OnTop, then they work.
https://bugs.chromium.org/p/chromium/issues/detail?id=1246668
I only tested OnTop, not any of the other layers.
Firefox is not affected.
$ icewm --version
IceWM 2.7.0.

**Comment by jidanni** [comment]
Using chrome in icewm,
visit https://scweb.cwb.gov.tw/en-US
Click "monitoring station searching" as in the photo.
If chrome's icewm layer is "Normal" nothing happens. Bug.
If chrome's icewm layer is "OnTop" we proceed correctly.

![20211002T213657](https://user-images.githubusercontent.com/1230959/135718800-b218da14-2c6f-4884-b1d3-9eda9bb3900d.jpg)

By the way, the above screenshot is when layer is set to OnTop.
If you take the same screenshot in Normal layer it will look like this:

![20211002T213135](https://user-images.githubusercontent.com/1230959/135718695-728946da-4718-44a2-95b4-04f131a58a8c.jpg)

I.e., the screen looks like it does in the first image. But when later you take a look at your screenshot, "a whole layer is missing!"

**Comment by gijsbers** [comment]
It makes no difference here which layer is used for chrome: always the same behavior.
The only thing which does make a difference is the size of the chrome window.
Since chrome uses only a single toplevel window and since all the subwindows are drawn by chrome inside its own toplevel window, icewm is never involved and hence it cannot be an icewm bug.

**Comment by jidanni** [comment]
Well all I know is: a tiny window, and a full screen window didn't
affect how the bug in
https://github.com/openstreetmap/openstreetmap-website/issues/3309
acted. But changing icewm's layer from Normal to OnTop did!

Same with
https://github.com/ice-wm/icewm/issues/62#issuecomment-932754209
except there was no way to test with a tiny window: the javascript
senses the size and converts to a cellphone menu arrangement.

**Comment by gijsbers** [comment]
What exactly is proven by your observation that changing the layer affects the behavior?

**Comment by jidanni** [comment]
> What exactly is proven by your observation that changing the layer affects the behavior?

If on a website clicking a menu item just causes the menu to close,
and taking a screenshot of the situation is impossible (unless using the root window),
that means you've got this bug #62. Solution: Change layer to OnTop.

**Comment by gijsbers** [comment]
That doesn't answer the question: What is proven?
There is no justification for this issue here.
Icewm cannot interfere with whatever your application draws.
It also doesn't handle application menus.
Hence this issue here is just a waste of our time.

**Comment by jidanni** [comment]
OK good.
So you verify you indeed see the behavior I described.
Seen in Normal mode, fixed in OnTop mode.
But you say it is not an icewm problem,
hence I should ask the chrome team to fix it.
Correct? Thanks.

**Comment by jidanni** [comment]
https://github.com/openinframap/openinframap/issues/70#issuecomment-934893440 menu on https://openinframap.org/ also affected. Clicking any checkbox will just close the menu, unless one is OnTop. I.e., the website thinks we are just clicking on some area outside the menu, and thus closes the menu. I.e., the menu is just shown to us, "but not shown to the browser".
