### ISSUE TITLE
Add vertical panel mode for widescreens.

### ISSUE THREAD

**Issue by danykey** [ice-wm/icewm#65]
IceWM is excellent lightweight project but unusable for me on widescreens.
Please add vertical panel mode.

**Comment by vsplesk** [comment]
Why closed this?

Its an excellent question. I also wonder sometimes how people handle this crazy 21:9 screens with only 1080px height. On Windows, you can put the taskbar aside and regain some height, but with ice, how?

**Comment by gijsbers** [comment]
You could also use the feature defined by `TaskBarWidthPercentage` and `TitleBarJustify`.
