### ISSUE TITLE
configure error: Packages SM and ICE are required for session mgmt.

### ISSUE THREAD

**Issue by juanma0599** [ice-wm/icewm#66]
Hello, I am on Debian and I want to try the latest version of icewm, I have installed the required packages shown on GitHub, however when I do the command ./configure I get the following output:

`checking for sm ice ... no`
`configure: error: Packages SM and ICE are required for session mgmt.`

I do not know how to proceed, if I need something or need to do a different step, I appreciate that you can help me!

**Comment by gijsbers** [comment]
Hello juanma0599. If you find managing packages difficult, then please follow the instructions near the bottom of the website https://ice-wm.org/, where it reads `Install package dependencies`. Or consult a Debian website or forum.
