### ISSUE TITLE
French translation update

### ISSUE THREAD

**Issue by marcelocripe** [ice-wm/icewm#68]
Hello Mr Gijsbers,

Please accept the Wallon translator's review of the icewm-icewm-1-4-branch-fr.po file.
He asked for help with the merge on the antiX Linux forum https://www.antixforum.com/forums/topic/icewm-how-to-request-a-merge-at-github-update-french-translation/.

https://github.com/marcelocripe/icewm_fr.po/blob/main/icewm-icewm-1-4-branch-fr.po

Thank you so much for programming and maintaining IceWM.

- - - - -

Olá Senhor gijsbers,

Por favor, aceite a revisão do tradutor Wallon do arquivo icewm-icewm-1-4-branch-fr.po.
Ele pediu ajuda para a mesclagem no fórum do antiX Linux https://www.antixforum.com/forums/topic/icewm-how-to-request-a-merge-at-github-update-french-translation/.

https://github.com/marcelocripe/icewm_fr.po/blob/main/icewm-icewm-1-4-branch-fr.po

Muito obrigado por programar e manter o IceWM.

**Comment by marcelocripe** [comment]
[icewm-icewm-1-4-branch-fr_11-07-2021.zip](https://github.com/ice-wm/icewm/files/7492450/icewm-icewm-1-4-branch-fr_11-07-2021.zip)

**Comment by gijsbers** [comment]
The Wiki and the FAQ explain how to contribute translations:
https://ice-wm.org/FAQ/#how-to-translate-icewm
Thanks a lot!
