### ISSUE TITLE
window list menu -- horizonal scrollbar not rendered unless vertical scrollbar also present

### ISSUE THREAD

**Issue by Corin-EU** [ice-wm/icewm#71]
This bug is present in v2.7.0 and is also present in latest v2.8.0.  It was not present in ancient v1 versions and possibly up to v2.6.0.

If the text in the WindowList meu exceeds the height of the window,  then a vertical scroll bar appears and has the colors specified in the theme file.

It text in the WindowList menu exceeds the width of the window, then an horizontal scroll bar should appear with appropriate colors as set by the theme,  the same as for the vertical scrollbar, but it does not -- just a black band where the scrollbar should be..   However if the height of the window is reduced to force the vertcial scrollbar to appear,then the horizontal scrollbar appears with the correct colors in place of the black band

If the height of the window is then increased so that the vertical scrollbar disapears, then the horizontal scrollbar reverts to the black band,

Also when the two scrollbars are present, the square at the bottom right of the window in the space between the end of the vertical scrollbar and the end of the horizonal  scrollbar is black but it should be the color of the WindowLisit background (as set by the theme).

This issues is present regardless of the scrollbar style set by the Look setting (gtk, metal, pixmap checked) in the theme file.

**Comment by gijsbers** [comment]
This was fixed one week ago in commit 5d83fb531a1fd6f36134fc1ae73feef4693d83d0: "Fix the horizontal scrollbar for the window list window."

**Comment by Corin-EU** [comment]
Thanks for the information. 

So fixed on bbidulock repository but not yet migrated over to the ice-wm repository.
