### ISSUE TITLE
Problems fullscreening wine programs in icewm 2.9.0

### ISSUE THREAD

**Issue by plomari** [ice-wm/icewm#73]
Since icewm 2.9.0, fullscreening wine programs (a game) doesn't make the taskbar disappear. Also, there are weird focus issues. I also see tearing, but this is probably because the driver doesn't recognize the game's window as fullscreened anymore. It was fine before icewm 2.9.0 (not sure which version exactly, but I'm using Debian unstable).

**Comment by gijsbers** [comment]
Debian unstable upgraded to 2.9.1. Does that help you?
If not, can you recommended a minimal tiny application for me
which repeats this behavior? (i don't wish to install game hoopla.)

**Comment by plomari** [comment]
I just tried 2.9.1. It's possible that it improved behavior somewhat, but it's still bad.
Before 2.9.0:
- starting the program makes it properly fullscreened
- you can alt+tab away (or switch workspaces), and if you go back, it's still properly fullscreened

With 2.9.0:
- starting the program makes it fullscreened, but with the taskbar always visible
- switching away and back with alt+tab or workspace shortcuts doesn't fix the always visible taskbar
- confusing focus issues with keyboard input going to background windows

With 2.9.1:
- starting the program makes it properly fullscreened
- but it acts like 2.9.0 when switching away once

**Comment by plomari** [comment]
Actually, the focus problems are gone with 2.9.1 too, just the taskbar visibility is broken.
I just saw the commit referencing this commit, I can try tomorrow or so.

**Comment by plomari** [comment]
Tried it now, using commit 0ea5a3c5cba86e9b9609614fc1dd013e03fc909c.
I can confirm that this seems to have fixed the fullscreen issues I reported in this issue.

**Comment by plomari** [comment]
Could it be that this bug was fixed with 2.9.2, but appeared again with 2.9.3?

**Comment by gijsbers** [comment]
It carries a different solution, which was intended to be at least equivalent, but if it fails, please provide me with a scenario that I can reproduce on my system using my wine installation. For example, wine comes with executables like notepad and wordpad and so on. Can you detail a reproducable scenario with that?

**Comment by plomari** [comment]
OK, I don't know how to make standard wine programs enter fullscreen, but here's a reproduction with a freely available game:
- install wine 32 bit (I used wine-5.0.3, the default in Debian unstable)
- create a new wine prefix (to avoid interference with the existing wine default installation), for example:
```
mkdir /tmp/winetemp
cd /tmp/winetemp
export WINEPREFIX=/tmp/winetemp
```
- run `winecfg`, and check "Emulate a virtual desktop" under the "Graphics" tab, click OK (leave the desktop size at 800x600)
- download and unpack https://www.trle.net/scadm/trle_dl.php?lid=455 (a relatively small Tomb Raider 4 custom level that manages to reproduce the problem, see https://www.trle.net/sc/levelfeatures.php?lid=455 - all other levels using tomb4.exe show the same problem, so it doesn't have to be that one)
- run `wine tomb4.exe -setup`
- select the current resolution of your screen in the combo box in the "Output Resolution" frame (if the resolution is mismatched, it will start windowed instead of fullscreened! if that happens you can kill the game and start it again to retry)
- click OK, the game starts
- the window should be fullscreened (like EWMH fullscreen mode, not just a maximized window)
- a loading screen appears, and then the main menu of the game appears
- use alt+tab or ctrl+alt+(number) to switch to a different window or virtual desktop, then back (I noticed that the bug doesn't happen if xdotool changes the desktop without keyboard or mouse user input)
- the game is back in fullscreen, except you see the taskbar on the bottom of the screen (this is the bug)
- bonus bug: the game seemingly doesn't react to input anymore, because the alt or ctrl key is "stuck", hitting these keys again make the enter key work again (probably a wine or X11 issue)

**Comment by gijsbers** [comment]
Perfect scenario! Here the focus was set to a subwindow, 
which was a new case. Works for me in fullscreen now.
There is still the bug that sometimes the taskbar won't
go away when the game is in fullscreen. Someday...

**Comment by hunter2k01** [comment]
Notice this issue in icewm 3.0.1 on FreeBSD

**Comment by gijsbers** [comment]
@hunter2k01 The same game? How to repeat it?

**Comment by hunter2k01** [comment]
> @hunter2k01 The same game?

No, I am using WINE Steam (through Suyimazu) and in the first game I've installed which is Team Fortress Classic the taskbar appears above the fullscreen window even in fullscreen mode.

**Comment by plomari** [comment]
3.0.1 doesn't seem to show any fullscreen regressions in my case.

**Comment by gijsbers** [comment]
It seems to depend on particulars of some wine apps. Wine uses a special focus model. The taskbar fullscreen code is hairy. To make progress, report on percentage of reproducability (reliability of occurrence) and give the output of the `icesh focusmodel` command.

**Comment by plomari** [comment]
I get "Globally" on my wine apps, if that matters.

**Comment by gijsbers** [comment]
Indeed and wine is the only one I know of. It could be helpful to learn if other "Globally" apps have the same fullscreen problem. That would make testing easier too.

**Comment by zaza42** [comment]
Wow, this solved the problem of fullscreen mpv, which also sometimes forgot the taskbar at the bottom. (Before that I used an always on top from script after every switch to fullscreen.) I think this is the same bug, because it started with version 2.9.0.

**Comment by gijsbers** [comment]
If it is the same bug, then `icesh -c mpv focusmodel` should output "Globally".

**Comment by zaza42** [comment]
```
$ icesh -c mpv focusmodel
0x6000002  focusmodel Passive
```
