### ISSUE TITLE
New fullscreen issue in 2.9.5 (yay!)

### ISSUE THREAD

**Issue by plomari** [ice-wm/icewm#85]
Fortunately, it's a mild bug that only happens with a single program (mpv, should be available in most distros):
```
mpv --fs --no-config https://avatars.githubusercontent.com/u/29124883
```
This displays the image in fullscreen, but the problem is that with 2.9.5, the icewm taskbar is visible and overlaps the bottom of the displayed image. If you toggle fullscreen and back with the `f` key, the taskbar disappears as it should. It also works correctly if you start in windowed mode (remove the `--fs`) and then enter fullscreen with `f`.

Other programs, that start fullscreened, do not have this problem. But maybe it's because they don't set the fullscreen hint before mapping the window or so.

I think 2.9.4 was OK, but not entirely sure.

**Comment by gijsbers** [comment]
Confirmed. When it starts in fullscreen, icewm activates it, but doesn't put it in the fullscreen layer.

**Comment by plomari** [comment]
Confirmed working.
