### ISSUE TITLE
How to add custom docks or tray icons?

### ISSUE THREAD

**Issue by plomari** [ice-wm/icewm#86]
I want a thing for custom notifications (like emails) on the taskbar. I'm willing to write my own code for that, but I'd like to ask what the best way to achieve this is.

I know there's the systray thing, which most other WMs and toolkits consider legacy:
https://specifications.freedesktop.org/systemtray-spec/systemtray-spec-0.3.html
For example, GTK has deprecated it, and (worse) castrated its functionality to almost nothing. 
Also, it looks hard to implement without a toolkit.

And then you can move any normal window from the taskbar area to the systray using the IceWM `winoptions` file. You could for example simply change the window icon to something else to reflect a changed status in the systray. But you can't interact with the systray icon at all.

Is there anything else that should be used?

**Comment by gijsbers** [comment]
DockApps is another option, but it isn't on the taskbar.
On the taskbar I'd go with a systray app.
The spec is outdated with regards to messages.
More recent functionality is part of the XEmbed spec.
Check out the yxembed.cc and the yxtray.cc of icewm for details.
There is also the alltray program to reparent an app to the tray.

**Comment by plomari** [comment]
Thanks for the explanations.

This all seems to require low level X11 code, reading ancient bad specs, and reading icewm source code.
Is there an example of a systray client somewhere?

`alltray` is useful, but on IceWM you can use the `winoptions` mechanism to achieve the same.
Actually, the `winoptions` mechanism would be sufficient if I could provide a custom menu.

**Comment by gijsbers** [comment]
The specs are not bad and you only need to get the basic protocol.
That will be the only way to provide  a menu.
Xlib is not that bad actually. If you want something else try:
https://stackoverflow.com/questions/1203451/how-to-write-an-application-for-the-system-tray-in-linux
There are many examples. Just search for code with _NET_SYSTEM_TRAY_OPCODE:
https://codesearch.debian.net/search?literal=1&perpkg=1&q=_NET_SYSTEM_TRAY_OPCODE
It would be helpful if you would blog a tutorial on how to write a systray app with a menu.

**Comment by zaza42** [comment]
You can use [yad](https://github.com/v1cont/yad) from shell scripts.

**Comment by gijsbers** [comment]
Indeed. See [here](https://yad-guide.ingk.se/notification/yad-notification.html). Includes examples.

**Comment by gijsbers** [comment]
Tcl/Tk looks easy: https://www.tcl.tk/man/tcl8.7/TkCmd/systray.html
