### ISSUE TITLE
Why are there two icewm github repositories?

### ISSUE THREAD

**Issue by rubyFeedback** [ice-wm/icewm#87]
I may be a bit drunk right now but ...

we have:

https://github.com/ice-wm/icewm

with about 10 issues

and:

https://github.com/bbidulock/icewm

with about 106 issues.

Are these both referring to icewm? I keep on finding this one here first
via a google search, but the other repository seems more active. Is
there a way to unify both and then deprecate/remove the other, if
both refer to the icewm window manager?

The existing issues could just be copy/pasted I think. Right now this
is a bit confusing to me, perhaps also to others.

**Comment by plomari** [comment]
Duplicate of what? I'd like to know too.
