### ISSUE TITLE
Keyboard layout indicator color.

### ISSUE THREAD

**Issue by sajcho** [ice-wm/icewm#90]
Hi.
The color of the keyboard layout indicator is defined in blue.
It would not be possible to make this color optional.
For example, as an entry in the preferences file.

**Comment by gijsbers** [comment]
Could you provide a picture of your current situation? What theme do you use?

**Comment by sajcho** [comment]
Theme - Shades of Grey
![screen](https://user-images.githubusercontent.com/49790678/164704707-b4b65392-657b-4fde-b5eb-1ea6d1b9ef81.png)

**Comment by gijsbers** [comment]
Thanks. Would it be OK if we reuse `ColorClockText` for the keyboard indicator?
Are you aware you can also use an icon for each keyboard layout?
Just add `cz.xpm` and whatever country code + `.xpm` to your ~/.icewm/icons/.
It can be a flag or a text. The size should preferably be 24x12.

**Comment by sajcho** [comment]
I apologize for the delay.
It's super. It works perfectly.
Thanks.
