### ISSUE TITLE
Tint2

### ISSUE THREAD

**Issue by maplee0** [ice-wm/icewm#91]
Hello!

Have to write to you because the official tint2 bug tracker on Gitlab is not working.

I'm a debian user, Debian 11 bullseye with IceWM installed from the standard debian bullseye repository.
I installed tint2 as a panel and disabled icewm taskbar.
Everything works fine besides taskbar behavior:
When there is only one app is run.
Clicking the task shows the window on the screen (toggles the task) as expected.
Clicking it second time the window dissapears (iconifies - minimizes the task) as expected.
But then clicking it many times doesn't change anything.
It doesn't get the window back.
Have to close the task by clicking the right mouse button.

The tint2 settings:
https://i.postimg.cc/3R2p9VVd/0.png

Bug:
https://i.postimg.cc/Bt9TJsF5/1.gif

It works fine when openbox is used as a WM.
I don't know it's the bug in tint2 or in IceWM.
Maybe you can help. Sorry for the bother.
Thanks to you!

**Comment by gijsbers** [comment]
Works fine here. You need to ask tint2.
