### ISSUE TITLE
How can I use tabbed windows on a laptop (no middle mouse button)

### ISSUE THREAD

**Issue by cheapy** [ice-wm/icewm#95]
I can grab the window title bar with my left mouse button and move it with my trackpad to the title bar of another window, but it doesn't understand that I am trying to merge the two windows.  Would it be possible to move the window to where the title bar is on top of the other and then press a particular key to tell it to merge them or add it as a tab?

TABBED WINDOWS

A window frame may contain multiple client windows. To realize this, drag the title bar with the middle mouse button, while holding down a shift key, onto the title bar of another frame. The two title bars will start to flash to indicate that they can merge. Release the mouse button to merge the client of the upper window to the lower frame. Now the lower frame will have multiple clients, called tabs. Use the KeyWinNext=Alt+F6 and KeySysWinPrev=Alt+Shift+Esc keys to select a tab, or use the QuickSwitch or use a submenu in the window menu.

**Comment by gijsbers** [comment]
What does your mouse look like? It has no scroll wheel you can press?
I'm open to suggestions for different ways to merge tabs. What do other WMs do?
Now it is hardcoded to Shift+Button2, but this could become configurable.
You still have 3.0.0, which has one important bug fixed in 3.0.1.

**Comment by cheapy** [comment]
It is a Dell Inspirion I7-7559 from 2016.  It has 2 buttons and a pad.  I usually leave the pad click turned off because many times it will left click accidentally if my hand touches the pad.  There is no scroll wheel or middle button.  I have seen systems where if you click both left and right mouse buttons at the same time, it registers as a middle button click, but I have not seen this feature in a WM before.  This reminds me of dragging tabs between browser windows, but I don't think I want it to unintentionally move a window into another.  

What if I was to left click and move the window title bar over the other one and while still holding the left mouse button hit the Insert key (or some other sensible key like Down or "t" or "m" that is on all keyboards).  It is hard to hold the left mouse button down and do a multi-key press. 

Maybe you can suggest something?

**Comment by gijsbers** [comment]
See bug #93 for why 3.0.1.

Thanks for your valuable feedback.
My first try is to make the mouse binding configurable.
Adding a hotkey like you propose is not bad either.
I see KWin has a menu to create and move tabs.

**Comment by cheapy** [comment]
I haven't tried the one Java app I use.  Thanks for letting me know.  Hopefully antiX will get 3.0.1 quickly.  Nobody has had trouble yet.

Yes, I like the idea of a configurable mouse button and optional hotkey.  That would work well I'm sure.  

For myself, I looked at the apps I use and almost all have tabs built in, but I'm sure there are other situations where this is really nice solution, and if you need help testing, just post here and I'll be happy to help.

**Comment by gijsbers** [comment]
By default MouseWinTabbing="Shift+Pointer_Button2". For your laptop this needs to be changed. You could try MouseWinTabbing="Shift+Pointer_Button1". Then drag a title bar with the left mouse button while holding down the shift key. If you don't like the shift key, you can change it, or even delete it, like MouseWinTabbing="Pointer_Button1". In this case merging tabs is always considered if you drag a title bar with the left mouse button over some other title bar.

**Comment by cheapy** [comment]
That sounds good.  I'll give it a try tonight when I get home.  Thanks again for all your efforts, here.

**Comment by cheapy** [comment]
Ok, I was now able to get it to merge the windows by using the Preferences menu option to change the trigger as you suggested and saving the modification.  

I can't actually see tabs on the window, yet, but I know that's on a separate ticket and will be happy to help test it.  

Thanks very much.
