### ISSUE TITLE
Branch and tag naming collision with upstream repository

### ISSUE THREAD

**Issue by Code7R** [ice-wm/icewm#97]
This issue has repeatedly hit my as Debian integrator. But it also might confuse regular users who are looking for icewm and don't know the background history.

Problem: the branch used here for release work is basically derived from bbidulock/icewm-1-4-BRANCH . So I prefer registering them in the same local repository as two sources so that I can switch between them back and forth or cherry-pick without hacks, etc.

But:
a) it uses the same name for branches
b) it uses the very same tag naming pattern - but commits on the release branch!

I could work around (a) (although reluctantly). But (b) is a problem. Once a such "wrong" tag (from whichever POV) is fetched, it gets stick and can only be replaced with the "right" tag with force flags or removing the old one.

Proposal:

give the tags and branches here a distinctive naming!
Something like:

release/icewm-1-4-BRANCH (for the release branch)
and
release/x.y.z (for the tags).

**Comment by gijsbers** [comment]
I'm not a git wizard at all, so I can't help you, but maybe you can alias or rename or whatever, sorry.
